conf/cmi/core.entity_form_display.node.apartment.default.yml
conf/cmi/core.entity_view_display.node.apartment.default.yml
conf/cmi/core.entity_view_display.node.apartment.teaser.yml
conf/cmi/field.field.node.apartment.field_publish_on_etuovi.yml
conf/cmi/field.field.node.apartment.field_publish_on_oikotie.yml
conf/cmi/field.storage.node.field_publish_on_etuovi.yml
conf/cmi/field.storage.node.field_publish_on_oikotie.yml
conf/cmi/search_api.index.apartment.yml

Added boolean fields enabling users to publish any apartment on oikotie or etuovi
Test:
Apartment should have fields for etuovi and oikotie (field_publish_on_{})
Elasticsearch index should have publish_on_{} boolean fields

ASU-541: added boolean fields for apartments, publish on etuovi / oikotie

---

public/modules/custom/asu_content/asu_content.module

Apartment is set unpublished when state of sale is set to sold
Make fresh (although drush cr should be enough)
What to do:
- Go to any apartment edit page
- Change the state of sale to "Sold"
- Save the entity
You should see:
After saving you should see a message telling that the apartment was unpublished
The entity should be unpublished

ASU-667: Automatic state change when apartment is set as sold.

---

conf/cmi/field.field.node.apartment.field_debt_free_sales_price.yml
conf/cmi/field.field.node.apartment.field_floor.yml
conf/cmi/field.field.node.apartment.field_floor_max.yml
conf/cmi/field.field.node.apartment.field_living_area.yml
conf/cmi/field.field.node.apartment.field_loan_share.yml
conf/cmi/field.field.node.apartment.field_maintenance_fee.yml
conf/cmi/field.field.node.apartment.field_parking_fee.yml
conf/cmi/field.field.node.apartment.field_room_count.yml
conf/cmi/field.field.node.apartment.field_sales_price.yml
conf/cmi/field.field.node.apartment.field_stock_end_number.yml
conf/cmi/field.field.node.apartment.field_water_fee.yml
public/modules/custom/asu_content/asu_content.module
public/modules/custom/asu_content/src/Plugin/ComputedField/PricePerSquareMeter.php
public/themes/custom/asuntotuotanto/asuntotuotanto.theme

Creates dummy apartment for project if no apartments are added to the new project.
Make fresh
Create new Project (with no field values)
Save the project
Open the newly created project
- Apartment list should have 1 apartment with empty dataset (created automatically)
Create another new project
This time use the Project create form's entity reference tool to create new apartment for the project 
- Just add apartment number, no need to add any new values
Save the Project
- Apartment list should have 1 apartment with the dataset you entered (only the manually created one)

Asu 735 create dummy apartment on project creation

---

azure-pipelines-release.yml

Making a release didn't trigger the build action on Azure. Compared code to public side, there has been set this change and it worked well.

Fix azure release trigger

---

public/modules/custom/asu_csv_import/asu_csv_import.module
public/themes/custom/asuntotuotanto/asuntotuotanto.theme

create new project
- leave all required fields empty
- add csv to importer
- save the project
No new apartments were created & added to the project.

Prevent submit handler from executing if required field is not set

---

public/themes/custom/asuntotuotanto/templates/content/node--apartment--full.html.twig
public/themes/custom/asuntotuotanto/templates/content/node--project--full.html.twig
public/themes/custom/asuntotuotanto/templates/views/project/views-view--project-apartments-listing.html.twig

All fields (including title) that are empty under Apartment's "Details" are now hidden. Also, logic for some other fields that might be empty, were updated (i.e., mainly different text shows up if those fields are empty).

ASU-1060: Hide empty fields in the apartments details page

---

public/themes/custom/asuntotuotanto/templates/content/node--apartment--full.html.twig
public/themes/custom/asuntotuotanto/templates/content/node--project--full.html.twig

On project page:
- updated apartments count to: >= 2
- application start and end time are shown only if they are set
On apartment page:
- application start and end time are shown only if they are set & are not expired (i.e. in the past)

ASU-1060: Update logic for empty fields and apartments count.

---

public/themes/custom/asuntotuotanto/templates/content/node--apartment--full.html.twig

I am not 100% sure if the **right_of_occupancy_payment** field should be included and shown in this template (this was not mentioned in the ticket), but according to the logic we have elsewhere (for example, in the project apartments table we have the logic that _if project type == HASO, show right_of_occupancy_payment field; and if project type == Hitas, show debt_free_sales_price field_), I thought it should be.
Also, I've made **two options** for if statement in the case right_of_occupancy_payment field should be shown on HASO apartments -- one is added and the other one is commented out (see the comment in the file). If right_of_occupancy_payment field should not be shown anyway, both will be removed.

ASU-1046: Update apartment template with newly created fields (and logic)

---

docker-compose.yml
public/modules/custom/asu_elastic/src/Plugin/search_api/data_type/FileIdToUrl.php

Takes the baseurl for indexed urls from env variables instead of request referer

Asu x indexing urls

---

public/themes/custom/asuntotuotanto/asuntotuotanto.theme

Updated header user menu cache context
Make fresh
Login as any customer or salesperson
Make sure caches are cleared
Go to a content page
Login as another user
Go to the same content page
You should see your own username/email address in header

add cache context to menu block

---

public/themes/custom/asuntotuotanto/templates/content/node--project--full.html.twig

On project's page, attachments are no longer forced to be downloaded. User can preview it with browser.

ASU-1300: stop forcing download

---

composer.json
composer.lock
public/modules/custom/asu_application/src/Entity/Application.php
public/modules/custom/asu_rest/src/Plugin/rest/resource/Initialize.php

Sql problems with xpression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column
`"SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'asuntotuotantotestnew.state.field_apartment_state_of_sale_target_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by: select apt.apartment_id, state.field_apartment_state_of_sale_target_id as `state`, count(apt.apartment_id) as `count`
from asu_application__apartment as apt
left join node__field_apartment_state_of_sale as state on apt.apartment_id = state.entity_id
group by apt.apartment_id; Array
(
)`

contains nonaggregated

---

composer.json
composer.lock
conf/cmi/core.extension.yml
conf/cmi/nocurrent_pass.settings.yml

Site is using suomi.fi to login users and there are case where email is not get it from suomi.fi. If user fill email address and try to save then Drupal gives error from not insert your current pw. This option now removes requirement to fill current pw because suomi fi login system is not using pw's.

Added no current pw because users login suomi and not need or know pw

---

public/modules/custom/asu_content/asu_content.module

Revert apartment update on project update hook #441 changes because it gives 504-error.

ASU: remove apartment update on project update hook

---

docker/openshift/Dockerfile

Override couple file size limits in php-overrides.ini which are set in the drupal-docker-base image initially to 32M, and raise them to 64M.

Dockerfile: Set max upload file size to 64M

---

conf/cmi/asu_user.external_user_fields.yml
public/modules/custom/asu_user/src/AuthService.php

The National Identification Number (aka NIN, or HETU = Henkilötunnus, or PIN = Personal Identification Number) is accessed with a field named "national_identification_number" in the apartment application service API.  Fix the asu_user requests to use the correct field name.

asu_user: Fix name of the external NIN field (ASU-1703)

---

public/modules/custom/asu_application/src/Form/ApplicationForm.php

Hide unpublished, reserved and solded apartments from application form
- make fresh
- re index both search api indexes https://asuntotuotanto.docker.so/fi/admin/config/search/search-api
- Go hitas  https://asuntotuotanto.docker.so/fi/asuntohaku/hitas or hasohttps://asuntotuotanto.docker.so/fi/asuntohaku/haso  listing page 
- Edit some project and set application ending date up to future and check also that all required values are set that project can get applications (No documentation so i dont know which values must be what... Good luck)
- i used Gunillantie 4 just extend ending date to future https://asuntotuotanto.docker.so/fi/node/7518
- now you can see on project page which apartments are sold, reserved...
- now click luo hakemus and check that only Vapaa apartments …

SATT-13: Hide unpulished, solded or reserved apartments

---

public/modules/custom/asu_application/src/Form/ApplicationForm.php
public/modules/custom/asu_content/asu_content.module
public/modules/custom/asu_content/src/Entity/Project.php
public/modules/custom/asu_elastic/src/Plugin/search_api/data_type/AsuDateTime.php

https://andersinno.atlassian.net/browse/SATT-8
The closing time for application forms were closing 2 hours before they were supposed to. Adding the time conversion to Finnish time before comparing it solves this issue.
`make fresh`
- Go to omistusasunnot -> Tutustu kohteeseen (any on going or closed one) edit the node 
- Go to aikataulut tab ![image](https://github.com/City-of-Helsinki/drupal-asuntotuotanto/assets/98033579/9694966c-1ae6-40ff-9f69-b65e55f7d668)
- Edit the "Hakuajan päättymisaika" So that the value is in the past
- Confirm you are not able to apply for appartments 
- Edit the "Hakuajan päättymisaika" So that the value is 30 min later than current your current time (Time now 12:00, Hakuajan päättymisaika 12:30 ![image](https://github.com/City-of-Helsinki/drupal-asuntotuotanto …

SATT-8: Website time works incorrectly

---

public/themes/custom/asuntotuotanto/asuntotuotanto.theme
public/themes/custom/asuntotuotanto/templates/views/project/views-view-table--project-apartments-listing.html.twig

Fix apartment page statuses. Current version is not show free statuses on project page.
https://andersinno.atlassian.net/browse/SATT-30
- make fresh
- go index apartment listing search index https://asuntotuotanto.docker.so/fi/admin/config/search/search-api
- now go haso or hitas listing page https://asuntotuotanto.docker.so
- check some New haettava is possible and check project apartment statuses
- now open that project in a new tab
- check and compare that apartment statuses are same
- you can open project on edit mode and check there apartment statuses
- you can also test Free text translation by adding it https://asuntotuotanto.docker.so/fi/admin/config/regional/translate

SATT-30: Apartment free status fix

---

conf/cmi/core.entity_form_display.user.customer.default.yml
public/modules/custom/asu_user/src/AuthService.php

Set a new user default language fi and show language selection on user edit form
- Setup suomifi authentication on local docker
- make fresh
- login some user which is not already login
- You can check on your database
- check that after login that user language is finnish

SATT-9: Default language fi and show language select on edit

---

public/modules/custom/asu_user/src/AuthService.php

Suomi authentication (SAML) user name already exists fix
- Setup suomi fi auhentication on your local
- make fresh or make up
- go user listing https://asuntotuotanto.docker.so/fi/admin/people
- create 1-2 a new users
- open sql and go check users_field_data table
- now edit those a new users name column value to Antero Asiakas_1 and Antero Asiakas_2....
- logout or open different browser or incognito mode front page
- now login on kirjaudu
- use OP and do the login
- check that you can login with Antero Asiakas
- check on database users_field_data that latest Antero Asiakas name is Antero Asiakas_XX

SATT-28: 28: saml authentication already exists fix

---

composer.json
composer.lock

Revert react package 1.3.5 to 1.3.4
- make fresh
- re-index apartment listing https://asuntotuotanto.docker.so/fi/admin/config/search/search-api/index/apartment_listing
- clear cache
- check that https://asuntotuotanto.docker.so/fi/asuntohaku/haso and https://asuntotuotanto.docker.so/fi/asuntohaku/hitas pages works

revert react 1.3.5 to 1.3.4

---

composer.json
composer.lock

Update react package which fix Haso and Hitas listing page status colors
- make fresh or make build drush-cr
- index apartment listing index https://asuntotuotanto.docker.so/fi/admin/config/search/search-api/index/apartment_listing
- clear caches on Drupal UI
- go check hitas and or haso listing pages that varattu (reserved) is red
- I needed hard refresh before color change shows

SATT-39: react package update 1.4

---

conf/cmi/asu_csv_import.haso_apartment_fields.yml
conf/cmi/core.entity_form_display.node.apartment.default.yml
conf/cmi/core.entity_view_display.node.apartment.default.yml
conf/cmi/core.entity_view_display.node.apartment.teaser.yml
conf/cmi/field.field.node.apartment.field_haso_fee.yml
conf/cmi/field.storage.node.field_haso_fee.yml
conf/cmi/language/fi/field.field.node.apartment.field_haso_fee.yml
public/themes/custom/asuntotuotanto/asuntotuotanto.theme
public/themes/custom/asuntotuotanto/templates/content/node--apartment--full.html.twig

Added HASO fee field to apartment content type and csv HASO importer
- make fresh
- go edit some project /admin/content
- on project editing form just scroll down on bottom of form
- click Lataa HASO csv-pohja (screenshot 1)
- open that .csv file and check that csv include HASO fee field
- now fill some values to HASO fee columns in csv file and save that file
- create a new project and fill required fields like taloyhtiö and adress
- save project node
- now edit that just created project node
- go huoneistot tab and add that csv-file what you just edited
- save node and check that you dont get errors
- now open some apartments which you add that haso fee and check that haso fee field has value
- also haso fee value should be display on apartment public side when you view …

SATT-54: Added HASO fee field in apartments

---

conf/cmi/search_api.index.apartment.yml
public/modules/custom/asu_elastic/src/Plugin/search_api/processor/SearchApiExcludeItemsFromIndex.php

Elastic search now index all apartments but it can be cause some problems. This new process will exclude all apartments which are not referenced any project
- You need production sql to test it
- make fresh
- index apartment search api index https://asuntotuotanto.docker.so/fi/admin/config/search/search-api/index/apartment
- open search api in browser e.g. http://localhost:9200/_search?size=6000&pretty=true
- cmd + f and search /8128
- node/8128 should not be in that elastic search result
```
"title" : "Kustinpolku 6 A0",
"url" : "https://asuntotuotanto.docker.so/fi/asuntohaku/hitas/asunto-oy-helsingin-postipaketti-kustinpolku-6/a0",
"uuid" : "1c0a70a0-4913-4776-99c3-f0535ac6c2a3",
```

SATT-56: exclude non project apartments on elastic search

---

conf/cmi/core.entity_view_display.node.apartment.default.yml
conf/cmi/search_api.index.apartment_listing.yml
conf/cmi/views.view.project_apartments_listing.yml
public/modules/custom/asu_content/asu_content.module
public/modules/custom/asu_content/src/BatchService.php
public/modules/custom/asu_content/src/Commands/AsuContentDrushCommands.php
public/modules/custom/asu_rest/src/Plugin/rest/resource/ElasticSearch.php
public/themes/custom/asuntotuotanto/templates/content/node--apartment--full.html.twig
public/themes/custom/asuntotuotanto/templates/views/project/views-view-table--project-apartments-listing.html.twig

Lots of minor changes on prices fields
- make fresh
- make shell and run drush ac-oth ***notice***
*** you can check before running the command how many lines are in database on **field_right_of_occupancy_payment** table and **node__field_haso_fee** and then after you have run the command. then you see the difference
- rebuild tracking information and re-index apartment listing search api https://asuntotuotanto.docker.so/fi/admin/config/search/search-api/index/apartment_listing
- https://asuntotuotanto.docker.so/fi/asuntohaku/hitas
- open some hitas apartment page
- check that there is Share of housing company loan value is that if filled so open edit apartment and check
- Also open hitas project on edit 
- click apartment tab
- open some apartment edit mode
- check that …

Satt 54 haso fee latest changes

---

docker-compose.yml
public/modules/custom/asu_application/src/Form/ReservedApartmentContactForm.php

Reserved apartment contact form salesperson email validation
- add **DRUPAL_DEFAULT_FORM_EMAIL** variable to docker-compose.yml
- make fresh
- index apartment listing search api index
- search and go apply for free apartment form
- I used https://asuntotuotanto.docker.so/fi/contact/apply_for_free_apartment?apartment=A5&project=529
- Fill form and check that everything works https://mailpit.docker.so/
- Easiest way to test default email address is edit code on ReservedApartmentContactForm.php

SATT-61: Reserved apartment contact email validation

---

composer.json
composer.lock

React component update 1.4.1 which fix listing pages empty price problem 
https://andersinno.atlassian.net/browse/SATT-60
- make fresh or make build drush-cr
- rebuild tracking information search api apartment listing https://asuntotuotanto.docker.so/fi/admin/config/search/search-api/index/apartment_listing
- go Haso listing page https://asuntotuotanto.docker.so/fi/asuntohaku/haso
- if you see apartment with empty Asumisoikeusmaksu
- open a new tab apartment by click tutustu
- click edit and then click Hintatiedot tab
- check that Luovutushinta and Alkuperäinen luovutushinta is empty
- if both values are empty then everything is ok
- Fill both values and save node (apartment)
- on terminal
- make shell and then drush cron
- now refresh Haso listing page …

SATT-60: React component 1.4.1 which fix listing prices

---

public/modules/custom/asu_content/src/BatchService.php
public/themes/custom/asuntotuotanto/asuntotuotanto.theme
public/themes/custom/asuntotuotanto/templates/content/node--apartment--full.html.twig

Latest Haso fee field related changes and fixes
- better field conditions on hitas and haso fields
- more functionality to fill a new HASO fee field
- make fresh
- make shell
- drush ac-oth
- login as admin to site
- rebuild tracking information and re-index apartment listing search api index https://asuntotuotanto.docker.so/fi/admin/config/search/search-api
- now go Haso listing page https://asuntotuotanto.docker.so/fi/asuntohaku/haso
- Open ramdomly apartments at different projects pages to tabs
- click edit and open Hintatiedot
- Every apartment should be
- Luovutushinta and Alkuperäinen asumisoikeusmaksu
- Luovutushinta and Alkuperäinen asumisoikeusmaksu **should** be same values if Indeksitarkistettu asumisoikeusmaksu and Tilatut muutostyöt is empty
- Luovutushinta and Alkuperäinen …

SATT-54: Latest HASO fee field related changes

---

composer.json
composer.lock
conf/cmi/views.view.project_apartments_listing.yml
public/themes/custom/asuntotuotanto/templates/views/project/views-view-table--project-apartments-listing.html.twig

Revert previous production deployment HASO-54 related template & react package changes so HITAS and HASO listings are still using field_right_of_occupancy_payment value.

SATT-66: Revert field_right_of_occupancy_payment

---

composer.json
composer.lock

Error encountered when accessing SAML authentication mapping configuration page
When attempting to access admin/config/people/saml/authmap, the following error occurs:
`Symfony\Component\Routing\Exception\InvalidParameterException: Parameter "uid" for route "samlauth.authmap_delete_form" must match "[^/]++" ("" given) to generate a corresponding URL. in Drupal\Core\Routing\UrlGenerator->doGenerate() (line 209 of core/lib/Drupal/Core/Routing/UrlGenerator.php).`
https://www.drupal.org/project/samlauth/issues/3424834

ASU-X: SAML authentication mapping configuration page

---

public/modules/custom/asu_application/src/Form/ApplicationForm.php

Fixing Sentry message about `$eventDispatcher is deprecated`
`
Deprecated function: Creation of dynamic property Drupal\asu_application\Form\ApplicationForm::$eventDispatcher is deprecated in Drupal\asu_application\Form\ApplicationForm::create() (line 82 of /var/www/html/public/modules/custom/asu_application/src/Form/ApplicationForm.php)
`

eventDispatcher is deprecated

---

conf/cmi/core.entity_view_display.node.apartment.default.yml
conf/cmi/views.view.project_apartments_listing.yml
public/themes/custom/asuntotuotanto/templates/content/node--apartment--full.html.twig
public/themes/custom/asuntotuotanto/templates/views/project/views-view-table--project-apartments-listing.html.twig

Since there is a new field field_haso_fee, there is a need to apply changes to the templates related to it.
- Hiding the table header for haso_fee.
- Changed the separator from , to . in right_of_occupancy_payment and alteration_price.
- Removed the hard coded € sign from desktop and mobile. Configured in view. 
Image from prod.
- Added thousand separator '  ' so that it is inline with hitas.
- Revised the logic for mobile view for the apartment listing so that it will present the right value according to the values set.

SATT-54: Twig template changes haso fee

---

public/modules/custom/asu_application/asu_application.install
public/modules/custom/asu_application/src/Entity/Application.php

Adding created by and is admin created fields to application data so problem solving is easier for future
https://andersinno.atlassian.net/browse/SATT-71
use **dev** database and setup saml settings that you can use suomi login
- make fresh
- go re-index both search api indexes https://asuntotuotanto.docker.so/fi/admin/config/search/search-api
- go people listing and get some salesperson user id https://asuntotuotanto.docker.so/fi/admin/people
- login as salesperson in different browser or incognito mode
- as salesperson go again people listing https://asuntotuotanto.docker.so/fi/admin/people
- now short by Viimeksi paikalla and add application e.g. Testi Äyrämö or Antero Asiakas on toimenpiteet column 
- HASO testi 2024 should work
- when application form is open that is …

SATT-71: Application created by and is admin created

---

public/modules/custom/asu_application/asu_application.install

Remove asu_application_grant_permissions hooks
```
In helfi_platform_config.module line 315:
Role (admin) not found.
```

SATT-69: remove asu_application_grant_permissions hooks

---

composer.lock
public/modules/custom/asu_user/src/AuthService.php
public/modules/custom/asu_user/src/Controller/AuthController.php

Update Samlauth & externalauth contrib modules for latest version. Also update & change asu_user custom module to match Samlauth changes
Required on docker-compose:
- ASU_HASH_KEY
- ASU_SAML_CERT
- ASU_SAML_SP
- DRUPAL_AUTH_TOKEN
- make fresh
- do not login as admin
- go https://asuntotuotanto.docker.so/
- go login and use suomi fi login
- you can use what ever option you want but...
- OP, AKTIA and testitunnistaja are easiest to test (for others you need to Google test accounts, my link to test accounts doesn't work anymore...)
- on testitunnistaja: you can check more test accounts on "Löydät lisätietoja käytettävissä olevista testitunnisteista [Palveluhallinnasta](https://palveluhallinta.suomi.fi/fi/tuki/artikkelit/5a82ef7ab03cdc41de664a2b)."
- Check that suomi fi login is working as …

SATT-68: Samlauth & externalauth module update & custom login module changes

---

public/themes/custom/asuntotuotanto/templates/block/block--language-block.html.twig
public/themes/custom/asuntotuotanto/templates/navigation/links--language-block.html.twig

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.
> Make sure to include this in the D10.3 upgrade https://github.com/City-of-Helsinki/drupal-asuntotuotanto/pull/577
* Use the language object which is set in [helfi_api_base_template_preprocess_default_variables_alter()](https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/173/files#diff-c6358d300a9a1d9956fb89a8182da48065f9342a0f9e4ff310dde94f523a6382R113).
* Make sure your instance is up and running on correct branch and that the Helfi API Base module is updated to latest version.
* `git checkout UHF-8909 && composer update drupal/helfi_api_base`
* `make fresh`
* Run `make drush-cr`
[UHF-8909]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …

UHF-8909 Language object refactor

---

docker/openshift/init.sh

Added init.sh file to fix
```
STEP 7/14: COPY docker/openshift/init.sh /
error: build error: building at STEP "COPY docker/openshift/init.sh /": checking on sources under "/tmp/build/inputs": copier: stat: "/docker/openshift/init.sh": no such file or directory
error: the build hki-kanslia-aok-asuntotuotanto-dev/asuntotuotanto-565 status is "Failed"
##[error]The process '/usr/local/bin/oc' failed with exit code 1
```

SATT-68: Added init.sh file

---

docker/openshift/cron-entrypoint.sh

Added cron-entrypoint.sh file to fix 
```
STEP 10/14: COPY docker/openshift/cron-entrypoint.sh /usr/local/bin/cron-entrypoint
error: build error: building at STEP "COPY docker/openshift/cron-entrypoint.sh /usr/local/bin/cron-entrypoint": checking on sources under "/tmp/build/inputs": copier: stat: "/docker/openshift/cron-entrypoint.sh": no such file or directory
error: the build hki-kanslia-aok-asuntotuotanto-dev/asuntotuotanto-566 status is "Failed"
```

SATT-68: Added cron-entrypoint.sh file

---

public/themes/custom/asuntotuotanto/templates/misc/project-apartments-listing.html.twig

Sentry give this:
```
Twig\Error\SyntaxError
Unexpected token "name" of value "title" ("end of print statement" expected).
```

Unexpected token name of value title

---

public/modules/custom/asu_application/src/Form/ApplicationForm.php

Fixing right_of_residence max value validation check
resulted in a `400 Bad Request` response:\n{\"right_of_residence\":[{\"message\":\"Tämän arvon on oltava pienempi tai yhtä suuri kuin 2147483647.\",\"code\":\"max_value\" 
- use dev database
- make fresh or make drush-cr
- rebuild and re-index apartment listing search api if you havent project already running
- logout as admin
- make shell
- drush uli --uid=104
- create application https://asuntotuotanto.docker.so/fi/asuntohaku/haso/haso-2024-toukokuu-testi-hasokatu-89
- check that Asumisoikeusnumero can max 2147483647 so if you trying to add higher number you should give error message
- try first higher number than 2147483647 and then lower or equal to 2147483647

SATT-83: residence number max value check

---

public/sites/default/settings.php

Disable user_expire cron
- make fresh
- go people listing admin/people
- enable all users on mass update "poista esto valituilta käyttäjiltä"
- go cron listing /admin/config/system/cron/jobs
- run HELfi api base module cron
- go back to user listing page and check that all uses all active

SATT-96: Disable user_expire

---

public/modules/custom/asu_application/src/Entity/Application.php
public/modules/custom/asu_application/src/Form/SalespersonApplicationForm.php

Showing draft or sent to django timestamp to salesperson when adding application behalf on customer
- make fresh
- rebuild track information and re-index search apartment 
- logout
- login as salesperson like uid 85
- login as salesperson
- go user listing page
- filter users by last logged in value
- select tero Äyrämö and click Tee hakemus uudelle käyttäjälle
- now you should see timestamps on application list
- login as tero uid 104 on other browser
- go edit some draft and kept that in draft
- now on salesperson browser refresh and check that timestamp is change and correct
- you can also try sent application and be sure that sent to django time is correct

SATT-89: Show latest update timestamp

---

public/modules/custom/asu_application/src/Form/ApplicationForm.php
public/themes/custom/asuntotuotanto/asuntotuotanto.theme

Related adding personal id check to application form it broke form after validation. Problem was apartment selection ajax which changed form id and theme hook didnt load correct template
- make fresh
- search api: rebuild trackinformation and re-index both indexes
- logout
- login as salesperson via uli
- go person listing page and "Luo hakemus uudelle käyttäjälle"
- add at least 2 apartments and leave some errors on the form 
- try to sent form with errors and check that form is looking ok after it shows errors

SATT-81: Apartment select ajax broke application form

---

public/themes/custom/asuntotuotanto/asuntotuotanto.theme

Fix project apartment listing page application status undefined array key warning
- make fresh
- rebuild tracking information and re-index apartment listing page
- logout
- go haso or hitas listing page
- open some project which has multiple apartments
- check on project page that apartment listing is showing status and color on apartment status
- you can also check on docker logs that you dont see `Undefined array key \"low\" in get_apartment_application_status()` on logs

SATT-105: Undefined array key application_status

---

public/modules/custom/asu_application/src/Form/ApplicationForm.php
public/modules/custom/asu_application/src/Plugin/Field/FieldWidget/MainApplicantWidget.php

Fixing: 
`PHP message: Uncaught PHP Exception Error: "Typed property Drupal\asu_application\Form\ApplicationForm::$eventDispatcher must not be accessed before initialization" at /var/www/html/public/modules/custom/asu_application/src/Form/ApplicationForm.php line 417`
and
`{"message":"Deprecated function: substr(): Passing null to parameter #1 ($string) of type string is deprecated in Drupal\\asu_application\\Plugin\\Field\\FieldWidget\\MainApplicantWidget->formElement() (line 126 of /app/public/modules/custom/asu_application/src/Plugin/Field/FieldWidget/MainApplicantWidget.php)`
- make fresh
- go check some application id on database which is sent to django
- open docker logs
- open application /application/x/edit
- check logs that you dont see any of those two errors

SATT-101: eventDispatcher and personal_id php errors and warnings

---

composer.json
composer.lock

After the deployment of 10.3.6 we can remove the audit ignore from composer.json

SATT-X: Remove audit ignore

---

conf/cmi/search_api.index.apartment.yml

Need to run `drush cim` to update the ELS configuration and then reindex.

ASU-1713: Add construction_year and completion_date to Apartment index on Elasticsearch

---

conf/cmi/core.entity_form_display.node.project.default.yml
conf/cmi/core.entity_view_display.node.project.default.yml
conf/cmi/core.entity_view_display.node.project.teaser.yml
conf/cmi/core.entity_view_display.node.project.teaser_admin.yml
conf/cmi/core.entity_view_display.node.project.teaser_media_bank.yml
conf/cmi/field.field.node.project.field_transfer_of_shares_date.yml
conf/cmi/field.field.node.project.field_use_complete_contract.yml
conf/cmi/field.storage.node.field_transfer_of_shares_date.yml
conf/cmi/field.storage.node.field_use_complete_contract.yml
conf/cmi/search_api.index.apartment.yml

- **ASU-1739: Add field "use_complete_contract" for project. Index it on Elasticsearch.**
- **ASU-1739: Add field_transfer_of_shares_date field to Project**
- **ASU-1739: Add field `project_transfer_of_shares_date` to elasticsearch**
Related PR: https://github.com/City-of-Helsinki/apartment-application-service/pull/496

ASU-1739: Add necessary fields to Drupal and ElasticSearch for new contract template
