conf/cmi/search_api.index.local_elasticsearch_index.yml
drush deploy
- Check that project fields are taken via reverse reference
=> update node reverse data

conf/cmi/core.entity_form_display.node.project.default.yml, conf/cmi/core.entity_view_display.node.project.default.yml, conf/cmi/core.entity_view_display.node.project.teaser.yml, conf/cmi/core.entity_view_display.node.project.teaser_admin.yml, conf/cmi/field.field.node.project.field_ownership_type.yml, conf/cmi/field.storage.node.field_ownership_type.yml, conf/cmi/language.content_settings.taxonomy_term.ownership_type.yml, conf/cmi/language/fi/field.field.node.project.field_ownership_type.yml, conf/cmi/language/fi/taxonomy.vocabulary.construction_materials.yml, conf/cmi/language/fi/taxonomy.vocabulary.energy_classes.yml, conf/cmi/language/fi/taxonomy.vocabulary.heating_options.yml, conf/cmi/language/fi/taxonomy.vocabulary.new_development_status.yml, conf/cmi/language/fi/taxonomy.vocabulary.ownership_type.yml, conf/cmi/language/fi/taxonomy.vocabulary.site_owners.yml, conf/cmi/search_api.index.local_elasticsearch_index.yml, conf/cmi/taxonomy.vocabulary.ownership_type.yml, public/modules/custom/asu_content/asu_content.module, public/modules/custom/asu_content/src/Plugin/search_api/data_type/IdToUrl.php
drush cim, drush cr
Search api has new datatype for urls.
Elastic index has url fields "project_url" and "apartment_url" fields derived from ids with the new datatype.
=> Asu 308 index project apartment url

conf/cmi/core.entity_form_display.node.project.default.yml, conf/cmi/core.entity_view_display.node.project.default.yml, conf/cmi/core.entity_view_display.node.project.teaser.yml, conf/cmi/core.entity_view_display.node.project.teaser_admin.yml, conf/cmi/field.field.node.project.field_ownership_type.yml, conf/cmi/field.storage.node.field_ownership_type.yml, conf/cmi/language.content_settings.taxonomy_term.ownership_type.yml, conf/cmi/search_api.index.local_elasticsearch_index.yml, conf/cmi/taxonomy.vocabulary.ownership_type.yml
drush cim, drush cr
There should be new taxonomy: ownership type
Project should have new field: ownership type
elastic index should have new field: project_ownership type
=> added ownership type taxonomy, new field to project and added the field to index

conf/cmi/language/fi/taxonomy.vocabulary.building_types.yml, conf/cmi/language/fi/taxonomy.vocabulary.districts.yml, conf/cmi/user.role.anonymous.yml, conf/cmi/user.role.authenticated.yml
updated user permissions
updated taxonomy translation configurations
=> add translation for taxonomies

conf/cmi/core.entity_form_display.node.project.default.yml, conf/cmi/core.entity_view_display.node.project.default.yml, conf/cmi/core.extension.yml, conf/cmi/field.field.node.project.field_tasks.yml, conf/cmi/field.storage.node.field_tasks.yml, conf/cmi/language.content_settings.taxonomy_term.tasks.yml, conf/cmi/taxonomy.vocabulary.tasks.yml, conf/cmi/ultimate_cron.job.elasticsearch_connector_cron.yml, public/modules/custom/asu_tasklist/README.md, public/modules/custom/asu_tasklist/asu_tasklist.info.yml, public/modules/custom/asu_tasklist/asu_tasklist.module, public/modules/custom/asu_tasklist/config/schema/asu_tasklist.schema.yml, public/modules/custom/asu_tasklist/src/Plugin/Field/FieldFormatter/AsuTaskListFormatter.php, public/modules/custom/asu_tasklist/src/Plugin/Field/FieldType/AsuTaskList.php, public/modules/custom/asu_tasklist/src/Plugin/Field/FieldWidget/AsuTaskListWidget.php
Make fresh
- Add new task terms
- Go to any project
- Change state for any task and write a description
- Save the project
- View the project. count ({Completed tasks count} / {all tasks count}) should be visible.
- Go back to edit. The state should have been saved.
=> Asu 423 tasklist

composer.json, patches/elasticsearch_connector_indexfactory_v2.patch, public/modules/custom/asu_csv_import/asu_csv_import.module, public/modules/custom/asu_csv_import/src/UploadFileHandler.php, public/modules/custom/asu_rest/src/Plugin/rest/resource/Mailinglist.php
Updated elasticsearch index patch
Refactored custom module code
Fixed problem with too large template file
=> Asu x fixes

public/modules/custom/asu_rest/src/Plugin/rest/resource/Filters.php
change translationtrait to stringtranslationtrait
=> use correct stringtranlslation trait

public/modules/custom/asu_rest/src/Plugin/rest/resource/Filters.php, public/modules/custom/asu_tasklist/assets/js/tasklist.js, public/modules/custom/asu_tasklist/asu_tasklist.libraries.yml, public/modules/custom/asu_tasklist/src/Plugin/Field/FieldWidget/AsuTaskListWidget.php, public/modules/custom/asu_translation/src/TranslationFileWriter.php
Added javascript to make tasklist more usable.
Added taxonomy machinename to filter endpoint
=> Asu 425 tasklist javascript

composer.json, conf/cmi/search_api.index.apartment.yml, patches/elasticsearch_connector_indexfactory_v3.patch
updated elastic patch
updated holding type property path
=> Asu x minor fixes

conf/cmi/search_api.index.apartment.yml, public/modules/custom/asu_elastic/README.md, public/modules/custom/asu_elastic/asu_elastic.module, public/modules/custom/asu_elastic/src/Plugin/search_api/data_type/FileIdToUrl.php, public/modules/custom/asu_elastic/src/Plugin/search_api/data_type/IdToUrl.php
Updated elasticsearch index with max_floor field
Added a way to index file urls to elasticsearch
Updated documentation
=> Asu x elastic addition

conf/cmi/core.entity_form_display.taxonomy_term.new_development_status.default.yml, conf/cmi/core.entity_view_display.taxonomy_term.new_development_status.default.yml, conf/cmi/field.field.taxonomy_term.new_development_status.field_machine_readable_name.yml, conf/cmi/search_api.index.apartment.yml, public/modules/custom/asu_content/src/Plugin/ComputedField/NewDevelopmentStatus.php
Added apartment state of sale to index
Changed new development status to enum
Make fresh
Edit some of the apartments, add value to state of sale field and save the apartments.
re-index the data to your local elasticsearch
Use your browser to check the local index
You should see:
apartment_state_of_sale field indexed in elasticsearch as enum
new development status field value should be enum
=> Asu 700 update enums

docker/openshift/Dockerfile, docker/openshift/docker-entrypoint.sh
added dockerfile & script for the environment
=> added dockerfile & script for the environment

public/modules/custom/asu_rest/src/Plugin/rest/resource/Content.php, public/modules/custom/asu_rest/src/Plugin/rest/resource/Filters.php
Make fresh
-Go to /filters
-See what districts are returned
-Go to any published project
-Change the project district to something that wasn't listed in the filters endpoint and save the project
- Go back to /filters
- The the new district should have appeared and old district should have disappeared from the district list
=> ASU-735: get the districts that have open projects

azure-pipelines-master.yml
Changed to match release workflow on the project. After this change, all
the code changes to develop branch will be triggered to dev and test
environment.
=> ASU-796 Change azure pipeline trigger to develop

public/modules/custom/asu_content/asu_content.routing.yml, public/modules/custom/asu_content/src/Controller/ApartmentContentCreateController.php, public/themes/custom/asuntotuotanto/asuntotuotanto.theme
1. `make fresh`
2. Check out project & apartment content and you might have content without images
3. Go to https://asuntotuotanto.docker.so/fi/apartment-content-script
4. Go check the content now, it should have generated some images
=> ASU-X: Generate content for project & apartment fields

public/sites/default/settings.php
Changed wrong key to correct one
=> Change environment key

public/sites/default/settings.php
Added cluster id for elasticsearch in settings
=> added cluster id to settings

conf/cmi/elasticsearch_connector.cluster.asuntotuotanto.yml
=> add prefix for index

public/sites/default/settings.php
=> Fixed wrong cluster id

public/sites/default/settings.php
Removed obsolete environment specific configurations
=> Removed obsolete environment specific configurations

public/modules/custom/asu_elastic/src/Plugin/search_api/data_type/Enum.php
add exception for apartment state of sale
=> add exception for apartment state of sale

public/modules/custom/asu_content/src/Plugin/ComputedField/NewDevelopmentStatus.php, public/modules/custom/asu_content/src/Plugin/ComputedField/ProjectBuildingType.php, public/modules/custom/asu_content/src/Plugin/ComputedField/ProjectHoldingType.php, public/sites/default/settings.php
=> english enum fixed, updated settings

public/modules/custom/asu_content/src/Plugin/ComputedField/ApplicationFormUrl.php
Make fresh
Check that you have projects with:
- NOW < field_application_end_time
- NOW > field_application_end_time
Index the projects to elastic
- You should see 2 different application urls:
1: Url to the application form
2: Url to contact form with query parameter "title"
=> Asu x index free application form url

public/modules/custom/asu_content/src/Plugin/ComputedField/ApartmentImages.php, public/modules/custom/asu_rest/src/Plugin/rest/resource/Content.php, public/sites/default/settings.php
Make fresh
Add floorplan image to any apartment
Index apartments
- image_urls key should contain floorplan image
Check the content endpoint for the apartment you edited
- images should now contain floorplan image
=> Asu 875 floorplan indexed images array

conf/cmi/search_api.index.apartment.yml, conf/cmi/user.role.admin.yml, conf/cmi/user.role.anonymous.yml, conf/cmi/user.role.authenticated.yml, conf/cmi/user.role.content_producer.yml, public/modules/custom/asu_rest/src/Plugin/rest/resource/Filters.php
updated permissions for rest endpoints
Added lines of codes to prevent notices.
=> Asu x persmission update

public/modules/custom/asu_rest/src/Plugin/rest/resource/Filters.php
added check that array key exists
=> check if array key is set

public/modules/custom/asu_content/src/Plugin/ComputedField/ApplicationFormUrl.php, public/sites/default/settings.php
Updated settings variables after updating server env variables
=> updated application baseurl

public/modules/custom/asu_content/src/Plugin/ComputedField/ApartmentImages.php, public/sites/default/settings.php
=> prevent exception on indexing

conf/cmi/search_api.index.apartment.yml, public/modules/custom/asu_content/src/Plugin/ComputedField/ApartmentUrl.php, public/modules/custom/asu_content/src/Plugin/ComputedField/ApplicationFormUrl.php, public/modules/custom/asu_content/src/Plugin/ComputedField/ProjectUrl.php, public/modules/custom/asu_rest/src/Plugin/rest/resource/Filters.php, public/sites/default/settings.php
Updated indexed urls.
Updated Settings parameters.
=> Asu x update content url

conf/cmi/views.view.project_apartments_listing.yml, public/modules/custom/asu_content/src/Plugin/ComputedField/ApartmentImages.php, public/sites/default/test.services.yml, public/themes/custom/asuntotuotanto/asuntotuotanto.theme, public/themes/custom/asuntotuotanto/templates/views/project/views-view-table--project-apartments-listing.html.twig
1. `make fresh`
2. Check that the project apartment listing application urls are working
=> ASU-X: Fix project apartment listing application urls

conf/cmi/user.role.anonymous.yml, conf/cmi/user.role.authenticated.yml, public/modules/custom/asu_rest/src/Plugin/rest/resource/Initialize.php, public/modules/custom/asu_rest/src/Plugin/rest/resource/Mailinglist.php
Drush deploy
Go to /fi/initialize
You should see "followed_projects_page_url" key in the json
you should see "followed_projects" key in the json, value should be an array (empty array or not empty)
=> Asu 465 follow project

conf/cmi/node.type.apartment.yml, conf/cmi/node.type.article.yml, conf/cmi/node.type.landing_page.yml, conf/cmi/node.type.news.yml, conf/cmi/node.type.page.yml, conf/cmi/node.type.service.yml, public/modules/custom/asu_user/asu_user.links.menu.yml, public/modules/custom/asu_user/asu_user.routing.yml, public/modules/custom/asu_user/asu_user.services.yml, public/modules/custom/asu_user/src/Commands/DeleteTestUsersCommands.php, public/modules/custom/asu_user/src/DeleteTestUsers.php, public/modules/custom/asu_user/src/Form/DeleteTestUsersForm.php
1. `make fresh`
2. Verify that you have "Delete all test users" men item under "People/Käyttäjät" in the toolbar
- Go to that page
3. You should see a button and when clicked deletes all users that start with "test_"
4. Go to terminal and `make shell`
5. Verify that you are able to run a custom drush command that will delete the test users as well
- `drush asu:dtu` or `drush asu:delete-test-users`
=> ASU-983: Delete test users script

public/modules/custom/asu_content/asu_content.module, public/modules/custom/asu_content/src/Plugin/ComputedField/ApplicationFormUrl.php
Prevented error while indexing
On testing-environment, index always after saving project.
=> index error

conf/cmi/asu_csv_import.haso_apartment_fields.yml, conf/cmi/asu_csv_import.hitas_apartment_fields.yml, conf/cmi/core.entity_form_display.node.apartment.default.yml, conf/cmi/core.entity_view_display.node.apartment.default.yml, conf/cmi/core.entity_view_display.node.apartment.teaser.yml, conf/cmi/field.field.node.apartment.field_right_of_occupancy_deposit.yml, conf/cmi/field.field.node.apartment.field_right_of_occupancy_fee.yml, conf/cmi/field.field.node.apartment.field_right_of_occupancy_payment.yml, conf/cmi/field.field.node.apartment.field_water_fee_explanation.yml, conf/cmi/field.field.node.project.field_street_address.yml, conf/cmi/field.storage.node.field_right_of_occupancy_deposit.yml, conf/cmi/field.storage.node.field_right_of_occupancy_fee.yml, conf/cmi/field.storage.node.field_right_of_occupancy_payment.yml, conf/cmi/language/fi/field.field.node.apartment.field_water_fee_explanation.yml, conf/cmi/search_api.index.apartment.yml, public/modules/custom/asu_csv_import/asu_csv_import.module, public/modules/custom/asu_csv_import/config/install/asu_csv_import.haso_apartment_fields.yml, public/modules/custom/asu_csv_import/config/install/asu_csv_import.hitas_apartment_fields.yml, public/modules/custom/asu_csv_import/src/ImportTypes/DecimalType.php, public/modules/custom/asu_csv_import/src/UploadFileHandler.php
Make fresh
Create new haso project, Don't save
Fill required fields
Download csv template
Fill the csv
Upload the file using the import upload field
Save node
New apartment should have been created as you entered them in csv file
Go back to the newly created project 
Download csv template for the project (HASO template) (Template should be prefilled with project apartments)
Change the values in csv file
Upload file
Save the project
Go check if the apartments are changed.
Repeat with new project with hitas template
Make sure the both hitas and haso template's fields matches description written in csv template story
Go to any apartment, update one of the new price fields
index apartments
Go check the index in elasticsearch
New price fields should be indexed as cents
=> Asu 1041 separate csv haso

public/modules/custom/asu_rest/src/Plugin/rest/resource/Initialize.php
Make fresh
Go to /fi/initialize
You should get react values
- React filter values should be lowercase keys
- Districts should only return selected districts from published projects
=> Asu 1034 initialize values

public/themes/custom/asuntotuotanto/asuntotuotanto.theme
1. `make fresh`
2. Check that the language switcher only has 1 language visible (finnish)
=> ASU-1025: Hide all but finnish in language switcher

docker/openshift/Dockerfile
=> ASU-1124: typo in folder name

public/modules/custom/asu_rest/src/Plugin/rest/resource/ElasticSearch.php
prevent notice caused by undefined array index.
=> ASU-1065: prevent notice on testing

public/modules/custom/asu_rest/src/Plugin/rest/resource/ElasticSearch.php
Property filtering must be lowercase
=> ASU-1065: Fixed propery case sensitivity

public/modules/custom/asu_apartment_search/composer.json, public/modules/custom/asu_apartment_search/composer.lock
Mostly for testing if testing deployment automation works
=> update apartment search module composer file

composer.json, composer.lock
File location had to be manually updated
=> package version had to be updated manually

composer.json, composer.lock, conf/cmi/autologout.role.admin.yml, conf/cmi/autologout.role.content_producer.yml, conf/cmi/autologout.role.customer.yml, conf/cmi/autologout.role.salesperson.yml, conf/cmi/autologout.role.supervisor.yml, conf/cmi/autologout.settings.yml, conf/cmi/core.extension.yml, conf/cmi/language/fi/autologout.settings.yml, conf/cmi/language/fi/block.block.footertopnavigation.yml, conf/cmi/language/fi/user.mail.yml, conf/cmi/language/sv/core.base_field_override.paragraphs_library_item.paragraphs_library_item.paragraphs.yml, conf/cmi/language/sv/core.entity_form_display.node.article.default.yml, conf/cmi/language/sv/core.entity_form_display.node.landing_page.default.yml, conf/cmi/language/sv/core.entity_form_display.node.page.default.yml, conf/cmi/language/sv/core.entity_form_display.paragraph.accordion.default.yml, conf/cmi/language/sv/core.entity_form_display.paragraph.accordion_item.default.yml, conf/cmi/language/sv/core.entity_form_display.paragraph.columns.default.yml, conf/cmi/language/sv/core.entity_form_display.paragraph.gallery.default.yml, conf/cmi/language/sv/core.entity_form_display.paragraph.list_of_links.default.yml, conf/cmi/language/sv/field.field.node.article.field_metatags.yml, conf/cmi/language/sv/field.field.node.landing_page.field_metatags.yml, conf/cmi/language/sv/field.field.node.page.field_metatags.yml, conf/cmi/language/sv/user.mail.yml, conf/cmi/language/sv/views.view.paragraphs_library.yml, conf/cmi/language/sv/views.view.scheduler_scheduled_content.yml, conf/cmi/user.role.anonymous.yml, public/modules/custom/asu_rest/src/Plugin/rest/resource/Initialize.php
I’ve set up Automated Logout module (https://www.drupal.org/project/autologout) and configured it in the following way: 
- it logs out all logged in users after 30 minutes of inactivity 
- before it logs user out, it asks him/her (modal) if s/he wants to stay logged in (user has 20 seconds to decide, then it automatically logs him/her out)
- I also disabled the option for “user-specific logout thresholds”, which means users cannot decide by themselves what logout treshold they will have (that is, after what time they will be logged out)
- status message in modal is not yet translated to Finnish or Swedish, though – this needs to be done by someone else, I suppose (/en/admin/config/people/autologout/translate)
=> ASU-836: ASU-1185: Install and configure Automated Logout module

public/modules/custom/asu_application/src/Entity/Access/ApplicationEntityAccess.php, public/modules/custom/asu_application/src/Entity/Application.php, public/modules/custom/asu_application/src/Form/ApplicationForm.php, public/modules/custom/asu_rest/src/Plugin/rest/resource/Initialize.php
Added links to login and register page for unauthenticated user trying to access application form.
=> Asu 1028 update application status message

public/modules/custom/asu_content/asu_content.module, public/themes/custom/asuntotuotanto/asuntotuotanto.theme, public/themes/custom/asuntotuotanto/templates/content/node--project--full.html.twig
Updated apartment count display & application time display in apartment / project pages.
Updated automated indexing for test environment.
=> Asu x small fixes

public/modules/custom/asu_apartment_search/composer.json, public/modules/custom/asu_apartment_search/composer.lock
Updated react version to 1.0.0
=> updated react version

composer.json, composer.lock, public/modules/custom/asu_apartment_search/README.md
Update root composer json also,
Updated react update instructions
=> update root composer.json, update readme instructions.

public/themes/custom/asuntotuotanto/templates/form/register/form--user-customer-register-form.html.twig
Wrong template name was used before, so I added the correct one.
=> ASU-1223: Fix register form style not applying

public/modules/custom/asu_api/src/Api/BackendApi/BackendApi.php
=> ASU-1214: add missing use statement

conf/cmi/core.entity_form_display.node.project.default.yml, conf/cmi/core.entity_view_display.node.project.default.yml, conf/cmi/core.entity_view_display.node.project.teaser.yml, conf/cmi/core.entity_view_display.node.project.teaser_admin.yml, conf/cmi/field.field.node.project.field_barred_bank_account.yml, conf/cmi/field.field.node.project.field_regular_bank_account.yml, conf/cmi/field.storage.node.field_barred_bank_account.yml, conf/cmi/field.storage.node.field_regular_bank_account.yml, conf/cmi/search_api.index.apartment.yml
Edit any existing project or create new
Add data to barred bank account and regular bank account fields
Re-index elasticsearch
New fields should be visible in elasticsearch with keys: project_barred_bank_account and project_regular_bank_account
=> Asu 1225 project account number fields

public/modules/custom/asu_api/src/Api/BackendApi/Request/CreateUserRequest.php, public/modules/custom/asu_user/asu_user.module, public/modules/custom/asu_user/src/RegisterForm.php
sometimes salesperson had missing fields, prevent errors
=> ASU-1225: missing fields with sales person

public/modules/custom/asu_elastic/src/Plugin/search_api/data_type/FileIdToUrl.php
use the proper functionality instead of reading the request
=> try using proper functionality to create the file url

conf/cmi/ultimate_cron.job.asu_content_cron.yml, public/modules/custom/asu_application/asu_application.module, public/modules/custom/asu_content/asu_content.module
Cron is removing drafts on approx. 30 day delay.
Create an application for project, save as draft
Update project's application end time to be 30 days from this day
Run cron
Your new application should have been deleted.
=> Asu x cron indexing

public/modules/custom/asu_elastic/src/Plugin/search_api/data_type/FileIdToUrl.php
Fixing elasticsearch cron indexing
=> changing env variable should fix the baseurl, reverting code change

public/modules/custom/asu_api/src/Api/BackendApi/BackendApi.php, public/modules/custom/asu_api/src/Api/BackendApi/Request/CreateApplicationRequest.php, public/modules/custom/asu_api/src/Api/BackendApi/Request/CreateUserRequest.php, public/modules/custom/asu_api/src/Api/BackendApi/Request/SalesCreateApplicationRequest.php, public/modules/custom/asu_api/src/Api/BackendApi/Request/UpdateUserRequest.php, public/modules/custom/asu_api/src/Api/Request.php, public/modules/custom/asu_application/asu_application.module, public/modules/custom/asu_application/src/Form/ApplicationForm.php
Prevent application form not being able to save due to ajax call
code fixes
=> Asu x update application form

public/modules/custom/asu_api/asu_api.services.yml
prod deployment requires service
=> add required service

composer.json, composer.lock, conf/cmi/core.extension.yml, conf/cmi/language/fi/block.block.footertopnavigation.yml, conf/cmi/language/fi/eu_cookie_compliance.cookie_category.essential.yml, conf/cmi/language/fi/hdbt_admin_tools.site_settings.yml, conf/cmi/matomo.settings.yml, conf/cmi/ultimate_cron.job.asu_application_cron.yml, conf/cmi/ultimate_cron.job.dblog_cron.yml, conf/cmi/ultimate_cron.job.matomo_cron.yml, conf/cmi/user.role.authenticated.yml
Installed & enabled Matomo module. Proper configurations couldn't be added since the Matomo credentials are missing
Make fresh
- Check that Matomo module is installed
=> Asu 951 matomo

public/modules/custom/asu_rest/src/Plugin/rest/resource/ElasticProxy.php
added missing plugin preventing deployment
=> ASU-X: Missing plugin

composer.lock
Update latest platform changes & drupal core security updates
=> updated platform & drupal core

public/modules/custom/asu_application/asu_application.module, public/sites/default/settings.php
=> update site settings for production

composer.lock, public/modules/custom/asu_application/asu_application.module, public/modules/custom/asu_rest/src/Plugin/rest/resource/ElasticProxy.php, public/sites/default/settings.php
Updated site settings for production
=> Release 23.12.2021

composer.json, conf/cmi/core.entity_form_display.user.sales.default.yml, conf/cmi/core.entity_form_display.user.user.default.yml, conf/cmi/core.entity_view_display.user.user.default.yml
Make fresh
Log in as sales person
Go to search tool
Result:
You should see apartment search tool
=> Asu x sales rest fix

public/modules/custom/asu_content/asu_content.links.menu.yml, public/modules/custom/asu_content/asu_content.routing.yml, public/modules/custom/asu_content/src/Form/BulkEditForm.php, public/modules/custom/asu_user/asu_user.links.menu.yml, public/modules/custom/asu_user/asu_user.routing.yml, public/modules/custom/asu_user/src/Controller/ListController.php
Log in as salesperson
Admin menu Tools submenu should have an item "apartment bulk upload"
=> added bulk edit link to admin menu for salesperson

conf/cmi/asu_rest.static_content.yml, conf/cmi/user.role.admin.yml, conf/cmi/user.role.authenticated.yml, conf/cmi/user.role.content_producer.yml, conf/cmi/user.role.salesperson.yml, public/modules/custom/asu_application/asu_application.module, public/modules/custom/asu_rest/src/Plugin/rest/resource/Initialize.php, public/themes/custom/asuntotuotanto/asuntotuotanto.theme
Make fresh
Salesperson should see url alias tab on content edit page
Salesperson should be redirected in correct place after clicking "read more" on apartment search page
=> Asu x update permissions

conf/cmi/system.site.yml, public/modules/custom/asu_rest/src/Plugin/rest/resource/Initialize.php
Make fresh
React district filter label returned as translated
Error page & front page set in configuration
=> Asu x updates

conf/cmi/language.content_settings.taxonomy_term.faq_category.yml, conf/cmi/language.content_settings.taxonomy_term.faq_haso.yml, conf/cmi/language.content_settings.taxonomy_term.faq_hitas.yml, conf/cmi/taxonomy.vocabulary.faq_category.yml, conf/cmi/taxonomy.vocabulary.faq_haso.yml, conf/cmi/taxonomy.vocabulary.faq_hitas.yml
FAQ taxonomy creation form default language to finnish
=> FAQ taxonomy default language finnish

public/modules/custom/asu_api/src/Api/BackendApi/BackendApi.php, public/modules/custom/asu_api/src/Api/BackendApi/Request/UpdateUserRequest.php, public/modules/custom/asu_api/src/Api/ClientFactory.php, public/modules/custom/asu_api/src/Helper/RequestHelper.php, public/modules/custom/asu_application/asu_application.module, public/modules/custom/asu_content/asu_content.module, public/modules/custom/asu_content/src/Entity/Apartment.php, public/modules/custom/asu_content/src/Entity/Project.php, public/modules/custom/asu_content/src/Plugin/ComputedField/ApplicationFormUrl.php, public/modules/custom/asu_content/src/ProjectUpdater.php, public/modules/custom/asu_content/tests/src/Functional/FieldTest.php, public/modules/custom/asu_user/asu_user.module
Log in as customer
Edit your account details
Save
Your credential should change
=> Asu 1244 user information update

composer.json, composer.lock, conf/cmi/core.extension.yml, conf/cmi/openid_connect.client.tunnistamo.yml, conf/cmi/openid_connect.settings.yml, patches/tunnistamo.patch, public/sites/default/settings.php
Make fresh
Change tunnistamo openid settings to make the login button visible
go to login page, click the new button
=> Asu 1266 authentication

composer.json, patches/tunnistamo_v2.patch
=> ASU-1266: update url

public/modules/custom/asu_application/asu_application.module, public/modules/custom/asu_application/src/Form/ApplicationForm.php, public/modules/custom/asu_application/templates/asu-application.html.twig
Application form saves as a draft properly
Added updated texts to applications page
Added rules to prevent locked text showing unless the application is actually locked
=> Asu 1298 application fixes

public/modules/custom/asu_rest/src/Plugin/rest/resource/Initialize.php
Change required because of the decision to keep projects in elastic was made.
=> ASU-1299: Return correct districts for the project

public/modules/custom/asu_rest/src/Plugin/rest/resource/Initialize.php
Get districts for only published apartments for react filters
=> ASU-1299: apartment must be published

conf/cmi/language/fi/user.mail.yml, public/modules/custom/asu_user/asu_user.module, public/modules/custom/asu_user/src/RegisterForm.php
Email sending on user registration, when sales creates customer account or sales creates sales account
=> Asu 1303 emails

public/themes/custom/asuntotuotanto/templates/views/faq/views-view--faq--faq-page-haso.html.twig
Updated template strings to be translatable
=> ASU-1329: add translation to template

conf/cmi/core.entity_form_display.node.project.default.yml, conf/cmi/core.entity_view_display.node.project.default.yml, conf/cmi/core.entity_view_display.node.project.teaser.yml, conf/cmi/core.entity_view_display.node.project.teaser_admin.yml, conf/cmi/field.field.node.project.field_upcoming_description.yml, conf/cmi/field.storage.node.field_upcoming_description.yml, conf/cmi/search_api.index.apartment.yml
new field in project's form
project_upcoming_description in elasticsearch
=> Added "upcoming description" field for project + indexed the new field

conf/cmi/language/fi/node.type.news.yml, conf/cmi/language/fi/views.view.news.yml, conf/cmi/user.role.admin.yml, conf/cmi/user.role.anonymous.yml, conf/cmi/user.role.authenticated.yml, conf/cmi/user.role.content_producer.yml, conf/cmi/user.role.editor.yml, conf/cmi/user.role.read_only.yml, public/themes/custom/asuntotuotanto/templates/views/news/common/views-view--news--news-attachment-common.html.twig, public/themes/custom/asuntotuotanto/templates/views/news/common/views-view--news--news-page-common.html.twig, public/themes/custom/asuntotuotanto/templates/views/news/haso/views-view--news--news-attachment-haso.html.twig, public/themes/custom/asuntotuotanto/templates/views/news/haso/views-view--news--news-page-haso.html.twig, public/themes/custom/asuntotuotanto/templates/views/news/hitas/views-view--news--news-attachment-hitas.html.twig, public/themes/custom/asuntotuotanto/templates/views/news/hitas/views-view--news--news-page-hitas.html.twig
=> updated news with translations

composer.json, composer.lock, conf/cmi/core.extension.yml, conf/cmi/raven.settings.yml, conf/cmi/ultimate_cron.job.content_lock_timeout_cron.yml, public/sites/default/settings.php
=> Asu 773 update sentry

public/modules/custom/asu_api/src/Api/BackendApi/Request/UserRequest.php, public/modules/custom/asu_user/asu_user.module, public/modules/custom/asu_user/src/RegisterForm.php, public/sites/default/settings.php
=> Asu 1314 helsinki profiili

public/modules/custom/asu_api/README.md, public/modules/custom/asu_content/README.md, public/modules/custom/asu_content/asu_content.module, public/modules/custom/asu_content/src/Entity/Project.php, public/modules/custom/asu_content/src/ProjectUpdater.php, public/modules/custom/asu_content/tests/src/Functional/ContentTest.php, public/modules/custom/asu_elastic/README.md, public/modules/custom/asu_rest/README.md, public/modules/custom/asu_user/README.md
tests for asu_content cron functionalities
=> Asu 1361 test cron functionalities

public/modules/custom/asu_content/README.md, public/modules/custom/asu_content/asu_content.module, public/modules/custom/asu_content/src/ProjectUpdater.php, public/modules/custom/asu_content/tests/src/Functional/ContentTest.php, public/modules/custom/asu_rest/src/Plugin/rest/resource/Initialize.php, public/modules/custom/asu_user/README.md
if apartment has no applications, set state to free for reservations
=> ASU-1361: add application status to logic

conf/cmi/asuntotuotanto.settings.yml, conf/cmi/field.field.media.image.field_media_image.yml, conf/cmi/field.field.node.apartment.field_images.yml, conf/cmi/field.field.node.project.field_shared_apartment_images.yml, conf/cmi/language/fi/views.view.faq.yml, public/modules/custom/asu_user/asu_user.module, public/themes/custom/asuntotuotanto/asuntotuotanto.theme, public/themes/custom/asuntotuotanto/templates/content/node--apartment--full.html.twig, public/themes/custom/asuntotuotanto/templates/content/node--project--full.html.twig
- Image alt texts are not required any more
- FAQ reset button translation
- Updated favicon
- ASU-1308 project's field_salesperson is on project & apartment templates
=> Asu x minor tweaks 2

composer.json, composer.lock, patches/platform_config_install.patch
commented out update hook failing to run
=> fix platform config install causing updb to fail

public/modules/custom/asu_content/asu_content.install, public/modules/custom/asu_content/asu_content.module
=> Asu 1447 publish a0 bydefault

composer.json, composer.lock, public/modules/custom/asu_apartment_search/README.md, public/modules/custom/asu_apartment_search/composer.json, public/modules/custom/asu_apartment_search/composer.lock
=> ASU-1448: updated react

composer.json, composer.lock
=> RELEASE 2 17-05-2022

public/modules/custom/asu_application/assets/js/additional-applicant.js, public/modules/custom/asu_application/src/Form/ApplicationForm.php, public/themes/custom/asuntotuotanto/templates/form/application/form--asu-application-haso-form.html.twig, public/themes/custom/asuntotuotanto/templates/form/application/form--asu-application-hitas-form.html.twig
Added minlength to pid field
Updated instructional texts
Added placeholder for pid field
=> update application form

public/modules/custom/asu_migration/src/ProjectMigrationService.php, public/modules/custom/asu_migration/src/UserMigrationService.php
=> ASU-1471: tweak fields

public/modules/custom/asu_application/asu_application.module, public/modules/custom/asu_migration/src/AsuMigrationBase.php, public/modules/custom/asu_migration/src/ProjectMigrationService.php, public/modules/custom/asu_migration/src/UserMigrationService.php, public/modules/custom/asu_migration/src/UuidService.php, public/modules/custom/asu_rest/src/Plugin/rest/resource/ElasticSearch.php, public/modules/custom/asu_rest/src/Plugin/rest/resource/Initialize.php
Updated apartment states with reserved  & vacant
Updated application form link urls
=> Asu 1480 apartment list visibility

composer.json, composer.lock
Update react package to 1.2.0
https://helsinkisolutionoffice.atlassian.net/browse/ASU-1536
=> ASU-1536: Update react package to 1.2.0

public/modules/custom/asu_content/asu_content.module
Presave apartment count field value automatically
https://helsinkisolutionoffice.atlassian.net/browse/ASU-1529
=> ASU-1529: apartment count

conf/cmi/search_api.index.apartment.yml, public/modules/custom/asu_elastic/asu_elastic.module, public/modules/custom/asu_elastic/src/Plugin/search_api/data_type/AsuDateTime.php
Elastic search date time fix 
https://helsinkisolutionoffice.atlassian.net/browse/ASU-1543
=> ASU-1543: elastic search datetime fix

public/modules/custom/asu_migration/src/AsuMigrationBase.php, public/modules/custom/asu_migration/src/ProjectMigrationService.php, public/modules/custom/asu_migration/src/UserMigrationService.php, public/modules/custom/asu_user/asu_user.module
Migration code changes e.g. separator ;
=> migration changes

public/modules/custom/asu_rest/src/Plugin/rest/resource/Initialize.php, public/sites/default/saml.settings.php
=> small fixes

public/modules/custom/asu_migration/src/ProjectMigrationService.php
=> migration fix

composer.json, composer.lock
Cannot load the Elasticsearch cluster for your index
https://www.drupal.org/project/elasticsearch_connector/issues/2850749
=> Cannot load the Elasticsearch cluster for your index

public/modules/custom/asu_migration/src/UserMigrationService.php
=> empty phone number

public/sites/default/saml.settings.php
Disable env check on saml settings
=> saml disable env check

public/modules/custom/asu_migration/src/UserMigrationService.php
Empty email to string not null
=> empty email string

public/modules/custom/asu_api/src/Api/BackendApi/Request/CreateUserRequest.php, public/modules/custom/asu_migration/src/UserMigrationService.php
Empty email value NULL to empty string.
=> email null to string

public/modules/custom/asu_migration/src/UserMigrationService.php
=> empty email

public/modules/custom/asu_migration/src/UserMigrationService.php
Dummy email value for empty and not valid data
=> dummy email

public/modules/custom/asu_api/src/Api/BackendApi/Request/CreateUserRequest.php
Drupal empty values (NULL) to empty string
=> null to empty string

public/modules/custom/asu_api/src/Api/BackendApi/Request/CreateUserRequest.php
empty string to __null__ string
=> null string

public/modules/custom/asu_migration/src/ProjectMigrationService.php
Fixes some pricing problems on migration script
=> apartment price fix

public/sites/default/saml.settings.php
=> saml entityid

public/sites/default/saml.settings.php
Saml security_metadata_sign on
=> saml AuthnRequestsSigned

public/sites/default/saml.settings.php
=> saml post to get

public/sites/default/saml.settings.php
=> saml url changes

public/modules/custom/asu_user/asu_user.routing.yml
Add no cache true on saml login routing
=> no cache true on saml login

public/sites/default/saml.settings.php
Saml error handling and redirect url
=> saml error handling

public/modules/custom/asu_user/src/AuthService.php, public/sites/default/saml.settings.php
=> Asu x saml changes

public/modules/custom/asu_user/src/AuthService.php
=> code standards

public/modules/custom/asu_user/src/AuthService.php
=> whitespace

public/modules/custom/asu_user/asu_user.routing.yml, public/modules/custom/asu_user/asu_user.services.yml, public/modules/custom/asu_user/src/Access/CustomValidCheck.php, public/themes/custom/asuntotuotanto/asuntotuotanto.theme
=> permission check

public/modules/custom/asu_user/src/AuthService.php
=> dump attributes

public/modules/custom/asu_user/src/AuthService.php
=> remove dump

public/sites/default/saml.settings.php
=> logout_different_user false

public/modules/custom/asu_user/asu_user.module, public/modules/custom/asu_user/asu_user.routing.yml, public/modules/custom/asu_user/src/AuthService.php, public/modules/custom/asu_user/src/Controller/AuthController.php, public/modules/custom/asu_user/src/Routing/RouteSubscriber.php, public/sites/default/saml.settings.php
=> latest saml changes

composer.json, composer.lock
React version update 1.2 to 1.3
=> ASU-1587: react version 1.3

public/modules/custom/asu_user/asu_user.module, public/modules/custom/asu_user/src/AuthService.php
Send user information to Django after user if created to Drupal
=> send external fields to django

public/modules/custom/asu_elastic/src/Plugin/search_api/data_type/AsuDateTime.php
Added timezone information to date time
=> ASU-1577: added timezone

composer.lock
=> Drupal core update 9.4.7

public/modules/custom/asu_content/asu_content.routing.yml, public/modules/custom/asu_content/src/Controller/ApartmentContentCreateController.php
Added endpoints to /healthz and /readiness which are now answering and give 200 response
=> ASU-1596: Add Kubernetes liveness and readiness probes

public/modules/custom/asu_elastic/src/Plugin/search_api/data_type/AsuDateTime.php
Change O to P for timezone value
=> ASU-1577: Change O to P

public/modules/custom/asu_api/asu_api.module, public/modules/custom/asu_api/src/Api/BackendApi/Request/GetApartmentStatusRequest.php
=> ASU-1501: aparment status

conf/cmi/asu_user.external_user_fields.yml, conf/cmi/ultimate_cron.job.asu_api_cron.yml, conf/cmi/user.settings.yml, public/modules/custom/asu_api/asu_api.module, public/modules/custom/asu_user/asu_user.routing.yml, public/modules/custom/asu_user/src/AuthService.php, public/themes/custom/asuntotuotanto/asuntotuotanto.theme, public/themes/custom/asuntotuotanto/templates/form/login/form--user-login-form.html.twig, public/themes/custom/asuntotuotanto/templates/layout/region--header-top.html.twig, public/themes/custom/asuntotuotanto/templates/user/user.html.twig
- Asu 1615
- Asu 1616
- Asu 1501
- Asu 1632
- Asu 1624
=> Asu 1640 merge

public/themes/custom/asuntotuotanto/asuntotuotanto.theme, public/themes/custom/asuntotuotanto/templates/form/login/form--user-login-form.html.twig, public/themes/custom/asuntotuotanto/templates/user/user.html.twig
Changes on login page / form
https://helsinkisolutionoffice.atlassian.net/browse/ASU-1615
=> ASU-1615: login form changes

conf/cmi/asu_user.external_user_fields.yml, public/modules/custom/asu_user/src/AuthService.php
External pid field which is used for sending pid value to django
https://helsinkisolutionoffice.atlassian.net/browse/ASU-1616
=> ASU-1616: pid field

public/modules/custom/asu_api/asu_api.module
=> ASU-1501: add logger

conf/cmi/ultimate_cron.job.asu_api_cron.yml, public/modules/custom/asu_api/asu_api.module
Disable apartment status update cronjob
=> ASU-1632: disable apartment status update

public/themes/custom/asuntotuotanto/templates/layout/region--header-top.html.twig
=> ASU-1624: hide login on header

public/modules/custom/asu_user/asu_user.routing.yml, public/themes/custom/asuntotuotanto/templates/layout/region--header-top.html.twig
Check this before #329
Disable /auth/login and /saml/login url's so user cant access to suomi fi login
=> Asu 1624 disable suomifi

conf/cmi/user.settings.yml, public/modules/custom/asu_user/asu_user.routing.yml, public/themes/custom/asuntotuotanto/templates/layout/region--header-top.html.twig
check this #330 before 
Disable user register that only admin can add users
=> Asu 1624 disable register

public/modules/custom/asu_application/src/Form/AskoApplicationForm.php, public/themes/custom/asuntotuotanto/templates/form/application/form--asu-application-haso-form.html.twig, public/themes/custom/asuntotuotanto/templates/form/application/form--asu-application-hitas-form.html.twig
Application back button url change to project page
=> ASU-1639: application back button

public/modules/custom/asu_application/translations/fi.po, public/modules/custom/asu_mailer/src/EventSubscriber/ApplicationSubscriber.php, public/modules/custom/asu_mailer/translations/fi.po, public/themes/custom/asuntotuotanto/templates/form/application/form--asu-application-haso-form.html.twig, public/themes/custom/asuntotuotanto/templates/form/application/form--asu-application-hitas-form.html.twig
Asko email message & hide second personal id field
=> Asu 1622 form changes

public/modules/custom/asu_application/src/Form/ReservedApartmentContactForm.php, public/modules/custom/asu_csv_import/src/ImportTypes/DecimalType.php, public/themes/custom/asuntotuotanto/asuntotuotanto.theme, public/themes/custom/asuntotuotanto/dist/js/intenseImages.min.js, public/themes/custom/asuntotuotanto/src/js/intenseImages.js, public/themes/custom/asuntotuotanto/templates/form/login/form--user-login-form.html.twig
Smalll translation fix and js open image fix
=> small changes

public/themes/custom/asuntotuotanto/templates/content/node--apartment--full.html.twig, public/themes/custom/asuntotuotanto/templates/form/application/form--asu-application-haso-form.html.twig, public/themes/custom/asuntotuotanto/templates/form/application/form--asu-application-hitas-form.html.twig
Hide personal id field on haso and hitas forms
=> hide second personal id

public/modules/custom/asu_rest/src/Plugin/rest/resource/Initialize.php
=> apartment statuses

public/modules/custom/asu_application/asu_application.module
Change register link and policy link order
=> register and pricy links reorder

public/modules/custom/asu_application/src/Form/ReservedApartmentContactForm.php, public/modules/custom/asu_content/src/Entity/Project.php, public/themes/custom/asuntotuotanto/asuntotuotanto.theme
Project id and apartment info to Apply for an apartment form emails
=> project id and apartment status

conf/cmi/field.field.asu_application.haso.field_personal_id.yml, conf/cmi/field.field.asu_application.hitas.field_personal_id.yml, public/themes/custom/asuntotuotanto/asuntotuotanto.theme
Old personal id required off and desimal 2 fix
=> personal id required off, number desical 2

conf/cmi/views.view.project_apartments_listing.yml, public/themes/custom/asuntotuotanto/templates/views/project/views-view--project-apartments-listing.html.twig
Hide A0 apartment on project page
Show 1 apartment on project page
=> A0 fix & show 1 apartment on project page

conf/cmi/swiftmailer.message.yml, public/modules/custom/asu_api/src/Api/AskoApi/Request/AskoApplicationRequest.php
Fixes these https://helsinkisolutionoffice.atlassian.net/browse/ASU-1645
=> ASKO email changes

composer.json, composer.lock
=> asuntomyynti/react 1.3.2

conf/cmi/core.entity_form_display.node.apartment.default.yml, conf/cmi/core.entity_view_display.node.apartment.default.yml, conf/cmi/core.entity_view_display.node.apartment.teaser.yml, conf/cmi/field.field.node.apartment.field_alteration_work.yml, conf/cmi/field.field.node.apartment.field_index_adjusted_right_of_oc.yml, conf/cmi/field.storage.node.field_alteration_work.yml, conf/cmi/field.storage.node.field_index_adjusted_right_of_oc.yml, conf/cmi/language/fi/field.field.node.apartment.field_alteration_work.yml, conf/cmi/language/fi/field.field.node.apartment.field_index_adjusted_right_of_oc.yml, conf/cmi/search_api.index.apartment.yml, public/modules/custom/asu_application/asu_application.module, public/themes/custom/asuntotuotanto/asuntotuotanto.theme, public/themes/custom/asuntotuotanto/templates/content/node--apartment--full.html.twig
Added a new fields to HASO:
Price due to cost index (indeksikorotuksien hintavaikutus, €) 
Price change due to alteration work (muutostöiden hintavaikutus, €)
=> ASU-1649: added adjusted & alteration price fields

public/modules/custom/asu_application/src/Form/AskoApplicationForm.php, public/modules/custom/asu_application/src/Plugin/Field/FieldWidget/ApartmentWidget.php
Haso project apartment adding fix
=> ASU-1649: project apartment add fix

conf/cmi/language.types.yml
remove user language user admin setting on language interface
=> ASU-1656: remove user language setting

public/modules/custom/asu_application/src/Form/ReservedApartmentContactForm.php, public/modules/custom/asu_content/src/Plugin/ComputedField/ApplicationFormUrl.php
Fix apply_for_free_apartment apartment value and form cache
=> ASU-1659: Fix apply_for_free_apartment url parameter

public/modules/custom/asu_application/src/Plugin/Field/FieldWidget/MainApplicantWidget.php, public/modules/custom/asu_content/translations/fi.po
Change personal id description last  to last 4
=> ASU-1658: personal id last 5 to last 4

conf/cmi/ultimate_cron.job.search_api_cron.yml, public/modules/custom/asu_application/src/Form/AskoApplicationForm.php
ASKO form apartment required. Also change search api cron time to 5min
=> ASU-1655: ASKO apartment required

public/modules/custom/asu_content/src/Plugin/ComputedField/ApplicationFormUrl.php
Trim and remove spaces out of apartment number value
=> Asu 1659 remove spaces

public/modules/custom/asu_application/src/Form/ReservedApartmentContactForm.php
apply_for_free_apartment email & date format fix
=> adding email and change date format

public/modules/custom/asu_application/src/Form/ReservedApartmentContactForm.php, public/modules/custom/asu_content/src/Plugin/ComputedField/ApplicationFormUrl.php
=> Release 22.12.

conf/cmi/ultimate_cron.job.asu_api_cron.yml, public/modules/custom/asu_api/README.md, public/modules/custom/asu_api/asu_api.module, public/modules/custom/asu_api/src/Api/BackendApi/Request/GetApartmentRevaluationsRequest.php, public/modules/custom/asu_api/src/Api/BackendApi/Response/GetApartmentRevaluationsResponse.php
=> ASU-1650: apartment revaluation api

public/modules/custom/asu_api/asu_api.services.yml, public/modules/custom/asu_api/src/Commands/SendApiCallCommands.php
=> ASU-1650: drush api debug

public/modules/custom/asu_api/README.md, public/modules/custom/asu_api/src/Api/BackendApi/BackendApi.php
=> ASU-1650: variable name update

conf/cmi/field.field.node.media_bank.field_media_bank_file.yml
=> ASU-1661: remove png support

conf/cmi/views.view.project_apartments_listing.yml, public/themes/custom/asuntotuotanto/asuntotuotanto.theme, public/themes/custom/asuntotuotanto/templates/content/node--apartment--full.html.twig, public/themes/custom/asuntotuotanto/templates/views/project/views-view-table--project-apartments-listing.html.twig
apartment listing price & apartment page price change
=> ASU-1680: apartment listing price & apartment page price change

conf/cmi/field.field.node.apartment.field_index_adjusted_right_of_oc.yml, conf/cmi/language/fi/field.field.node.apartment.field_index_adjusted_right_of_oc.yml, public/themes/custom/asuntotuotanto/templates/content/node--apartment--full.html.twig
Change term : Index adjusted right of occupancy payment to Index adjustment
=> Index adjustment term change

conf/cmi/node.type.media_bank.yml
=> ASU-1661: content type description

public/modules/custom/asu_application/src/Form/ApplicationForm.php, public/modules/custom/asu_application/src/Form/AskoApplicationForm.php
Hide a0 apartment on application form apartment select list
=> hide a0 on applicatition form select

public/modules/custom/asu_content/src/Entity/Project.php
Fixing "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'base.main_applicant__first_name'" error on project page
=> ASU-X-Application_count_fix

public/themes/custom/asuntotuotanto/asuntotuotanto.theme
Fix Haso and Hitas application form end datetime timezone
=> hitas & haso enddate time format fix

public/modules/custom/asu_content/src/Entity/Apartment.php, public/themes/custom/asuntotuotanto/asuntotuotanto.theme
=> Release 7.3. createTitle empty string fix

public/modules/custom/asu_api/src/Api/AskoApi/Request/AskoApplicationRequest.php
Fix personal id 4 char fix. 4 character personal id cut to 3 characters.
=> Personal id 4 char fix

public/modules/custom/asu_rest/src/Plugin/rest/resource/ElasticSearch.php
Clean asu_rest post fields list
=> clean rest fields

public/modules/custom/asu_rest/src/Plugin/rest/resource/ElasticSearch.php
More rest api post field cleaning
=> more fields cliening

public/modules/custom/asu_rest/src/Plugin/rest/resource/ElasticSearch.php
Change rest fields looping faster
=> change looping

public/modules/custom/asu_content/src/Plugin/ComputedField/MultipleValues.php
=> Computed field static cache

conf/cmi/core.entity_view_display.node.project.teaser_media_bank.yml
Mediabank slider settings same as project page slider
=> mediabank slider fix

conf/cmi/search_api.index.apartment_listing.yml, public/modules/custom/asu_rest/src/Plugin/rest/resource/ElasticSearch.php
Apartment listing page own elastic search index
=> Apartment listing index

public/modules/custom/asu_content/asu_content.module, public/modules/custom/asu_rest/src/Plugin/rest/resource/ElasticSearch.php
=> Do not cache empty data

public/modules/custom/asu_content/asu_content.module, public/modules/custom/asu_rest/src/Plugin/rest/resource/ElasticSearch.php
Fix and change search api indexing and lower cache time to 1h
=> Fix search api indexing and lower cache time

public/modules/custom/asu_content/asu_content.module
Change cache clear inside condition on entity update
=> Change cache clear inside condition

conf/cmi/search_api.index.apartment_listing.yml, public/modules/custom/asu_rest/src/Plugin/rest/resource/ElasticSearch.php
Added ASU-X-Cache_clear_entity_udpate to search api listing index and whitelist
=> added field_estimated_completion

public/themes/custom/asuntotuotanto/asuntotuotanto.theme, public/themes/custom/asuntotuotanto/templates/content/node--apartment--full.html.twig
Display more fields on apartment page
=> More fields apartment frontend page

public/themes/custom/asuntotuotanto/templates/content/node--apartment--full.html.twig
Adding water and parking fields suffix on template
=> Apartment parking and water suffix

composer.json, composer.lock, public/modules/custom/asu_rest/src/Plugin/rest/resource/ElasticSearch.php
ASU 1688 drupal side changes https://github.com/City-of-Helsinki/asuntomyynti-react/pull/85
=> ASU-1688: ASu 1688 drupal changes

public/modules/custom/asu_content/src/Entity/Project.php
Undefined array key 0 in Drupal\\asu_content\\Entity\\Project->getApplicationUrl() line 89
=> getapplication url check null

public/modules/custom/asu_api/asu_api.module
asu api change revaluation cron code
=> Fix asu cron revaluation

public/modules/custom/asu_content/asu_content.module
Remove immediately index on entity update
=> remove immediately index on entity update

public/modules/custom/asu_api/asu_api.module, public/modules/custom/asu_content/asu_content.module
=> Release 30.5.

public/modules/custom/asu_api/src/Api/BackendApi/Request/CreateApplicationRequest.php
Fix and test application form get applicant
=> Fix get Applicant feature

public/modules/custom/asu_application/asu_application.module, public/modules/custom/asu_content/src/Controller/ApartmentContentCreateController.php, public/modules/custom/asu_rest/src/Plugin/rest/resource/Content.php, public/modules/custom/asu_translation/src/TranslationFileWriter.php
Check custom modules for deprecated code
=> Check custom code for depracated code

public/modules/custom/asu_content/asu_content.module
Update project apartments and elastic search when project is updated.
=> Update apartments and elastic when project is udate

public/themes/custom/asuntotuotanto/templates/layout/region--header-top.html.twig, public/themes/custom/asuntotuotanto/templates/navigation/menu--main--mobile.html.twig
=> Hide login links

public/modules/custom/asu_application/src/Form/ReservedApartmentContactForm.php
=> ASU: Contact form bug fix

conf/cmi/ultimate_cron.job.asu_clear_cache_cron.yml, public/modules/custom/asu_clear_cache/asu_clear_cache.module
change custom clear cache cron to run every 5min
=> Clear cache cron to run every 5min

public/sites/default/saml.settings.php
Change Suomi.fi authentication stage entity id value
=> Change suomifi stage entity id

public/sites/default/saml.settings.php
Add ASU_SP_ENTITY_ID to server variables
=> ASU_SP_ENTITY_ID to server variables

public/modules/custom/asu_clear_cache/asu_clear_cache.module, public/modules/custom/asu_migration/src/ProjectMigrationService.php
Cache clear cron settings changes and migration fixes
=> Cache clean cron setting change and migration changes

public/modules/custom/asu_api/asu_api.module
Revert getApartmentRevaluation cron codes
=> Revert getApartmentRevaluation cron codes

public/modules/custom/asu_migration/src/ProjectMigrationService.php
- Fix code error getFilesFromTmp() to self::getFilesFromTmp()
- Passthrough empty district value so project is saved even district is empty
=> Migration fixes

public/modules/custom/asu_api/asu_api.module, public/modules/custom/asu_migration/src/ProjectMigrationService.php
=> Release (2) 21.9

conf/cmi/core.entity_form_display.asu_application.haso.default.yml, conf/cmi/core.entity_view_display.asu_application.haso.default.yml, conf/cmi/field.field.asu_application.haso.field_is_new_permit_number.yml, conf/cmi/field.storage.asu_application.field_is_new_permit_number.yml, public/modules/custom/asu_api/src/Api/BackendApi/Request/CreateApplicationRequest.php, public/modules/custom/asu_api/src/Api/BackendApi/Request/SalesCreateApplicationRequest.php, public/modules/custom/asu_application/asu_application.module, public/modules/custom/asu_application/src/Entity/Application.php, public/modules/custom/asu_application/src/Form/ApplicationForm.php, public/themes/custom/asuntotuotanto/templates/form/application/form--asu-application-haso-form.html.twig
Is new permit number selection to application form
=> ASU-1689: is new permit number selection

conf/cmi/field.field.asu_application.haso.field_is_new_permit_number.yml, public/themes/custom/asuntotuotanto/templates/layout/region--header-top.html.twig, public/themes/custom/asuntotuotanto/templates/navigation/menu--main--mobile.html.twig
revert login links #445 and fix permit number description text
=> Rever login links back and change permit_number desc

public/modules/custom/asu_application/src/Entity/Application.php
- Send revert is new permit number
=> Send revert new permit value

public/modules/custom/asu_api/src/Api/BackendApi/BackendApi.php, public/modules/custom/asu_application/src/EventSubscriber/ApplicationSubscriber.php
- Guzzle timeout setting change
=> Guzzle timeout change

public/modules/custom/asu_api/src/Api/BackendApi/BackendApi.php
increase authenticate timeout 60
=> authenticate timeout 60

public/modules/custom/asu_api/src/Api/BackendApi/BackendApi.php, public/modules/custom/asu_application/src/EventSubscriber/ApplicationSubscriber.php
=> Release 18.10

public/modules/custom/asu_application/src/Plugin/Field/FieldWidget/MainApplicantWidget.php
Admin can sent user application form
=> Admin sent application form by user

public/modules/custom/asu_application/src/Form/ApplicationForm.php
Check personal id value length before api call
=> check personal id length

public/modules/custom/asu_application/src/Plugin/Field/FieldWidget/MainApplicantWidget.php
admin / sales person send applicant form
=> local storage delete token

public/modules/custom/asu_application/src/Plugin/Field/FieldWidget/MainApplicantWidget.php
Fix sales account get applicant data
=> sales account fix for getting applicant

public/modules/custom/asu_api/src/Api/BackendApi/Request/SalesCreateApplicationRequest.php
=> set personal id to api call

public/modules/custom/asu_user/asu_user.module
Re-create sales person profile to django is local storage values are empty.
=> Re-create sales person profile to django

conf/cmi/asu_user.external_user_fields.yml, public/modules/custom/asu_api/src/Api/BackendApi/Request/CreateUserRequest.php, public/modules/custom/asu_application/src/EventSubscriber/ApplicationSubscriber.php, public/modules/custom/asu_application/src/Form/ApplicationForm.php, public/modules/custom/asu_user/src/AuthService.php
Latest pid and profile changes and fixes for Drupal side
=> Latest pid and profile fixes

public/modules/custom/asu_application/src/EventSubscriber/ApplicationSubscriber.php
Fix customer load to project uid not uuid
=> fix customer load to project  uid not uuid

public/modules/custom/asu_application/src/EventSubscriber/ApplicationSubscriber.php
load customer application owner id not project uid
=> get customer for owner id

public/modules/custom/asu_application/src/Form/ApplicationForm.php
Has applicant checks and validations
=> Application form applicant checks

public/modules/custom/asu_application/src/Form/ApplicationForm.php
Fix previous fix typo fix on condition #487
=> Condition fix

public/modules/custom/asu_user/asu_user.routing.yml, public/themes/custom/asuntotuotanto/templates/form/login/form--user-login-form.html.twig, public/themes/custom/asuntotuotanto/templates/layout/region--header-top.html.twig
Hide login link and disable suomifi login
=> Hide login link and disable suomifi

public/themes/custom/asuntotuotanto/templates/navigation/menu--main--mobile.html.twig
=> hide mobile link

public/modules/custom/asu_user/src/Routing/RouteSubscriber.php
=> reigster access false

public/modules/custom/asu_user/asu_user.routing.yml, public/modules/custom/asu_user/src/Routing/RouteSubscriber.php, public/themes/custom/asuntotuotanto/templates/form/login/form--user-login-form.html.twig, public/themes/custom/asuntotuotanto/templates/layout/region--header-top.html.twig, public/themes/custom/asuntotuotanto/templates/navigation/menu--main--mobile.html.twig
Revert login changes back to in place
- #493
- #495
- #496
=> SATT-21: Revert login changes

conf/cmi/search_api.index.apartment.yml, conf/cmi/search_api.index.apartment_listing.yml
Added Release_price field value to search api indexes
=> SATT-24: Added release_payment to search api indexes

conf/cmi/search_api.index.apartment.yml
Added field_stock_start_number and field_stock_end_number to elastic search
=> SATT-29: stock start and stock end numbers to elastic

public/modules/custom/asu_api/src/Plugin/SyncApplication.php, public/modules/custom/asu_application/src/ApplicationListBuilder.php, public/modules/custom/asu_application/src/Entity/Application.php, public/modules/custom/asu_application/src/Form/ApplicationForm.php, public/modules/custom/asu_content/src/Form/BulkEditForm.php, public/modules/custom/asu_user/src/Customer.php, public/themes/custom/asuntotuotanto/asuntotuotanto.theme, public/themes/custom/asuntotuotanto/templates/paragraph/paragraph--image--news.html.twig
Fixing errors with protected member visibility.
Twig template fix for apply spaceless.
`make fresh`
- Go to any any kohde (e.g `fi/node/6985`) and confirm you can see the email of the salesperson
- Go to any huoneisto and confirm you can see the email of the saleperson
- Go to any uutiset content type and add a paragraph with image
- Confirm you can save the node and that the picture shows up on the site
- Confirm you are able to open the HASO application with an account with the role "customer"
- Give yourself the Admin and salesperson roles. Go to: https://asuntotuotanto.docker.so/fi/admin/apartment/bulk-edit
- Confirm you can do a bulk edit for images
- Go to: https://asuntotuotanto.docker.so/fi/admin/content/application
- Confirm that the page loads and you can see the list of …
=> SATT-19: Protected member visibility

.env
=> Disable file sync on local

composer.json, composer.lock
- update react pack 1.3.4 to 1.3.5
=> SATT-30: update react pack 1.3.4 to 1.3.5

public/modules/custom/asu_content/src/Entity/Project.php, public/modules/custom/asu_rest/src/Plugin/rest/resource/Content.php
- Search api application url lang fix
=> Search api application url lang fix

public/sites/default/settings.php
Fix elastic search api host problem
- make fresh or make drush-cr
- Go page https://asuntotuotanto.docker.so/fi/admin/config/search/search-api/server/asuntotuotanto and check that is opens without errors
=> Elastic search host fix

composer.json, composer.lock
=> ASU-X: React package update 1.3.8

public/themes/custom/asuntotuotanto/src/scss/06_components/content/project/_project-apartments.scss
Apartment status high color to green follow up #533
=> SATT-39: high color to green

composer.lock
Registration role module security update
=> registration_role security update

conf/cmi/symfony_mailer_lite.symfony_mailer_lite_transport.smtp.yml, public/sites/default/settings.php
Fix and changes previous changes #555
=> SATT-58: Email settings changes

public/modules/custom/asu_content/src/BatchService.php
Related #561 pr. Code standards fix
=> SATT-54: BatchService.php codestandard fix

public/modules/custom/asu_content/src/Plugin/ComputedField/ApplicationFormUrl.php
Fix ticket https://andersinno.atlassian.net/browse/SATT-62
- make fresh
- rebuild tracking information and re-index apartment listing search api https://asuntotuotanto.docker.so/fi/admin/config/search/search-api/index/apartment_listing
- Go hitas and haso listing pages and check that Ota yhteyttä links are linking forms
- https://asuntotuotanto.docker.so/fi/asuntohaku/hitas
- https://asuntotuotanto.docker.so/fi/asuntohaku/haso
=> SATT-62: Elastic search apartment application url fix

composer.lock, conf/cmi/asu_csv_import.haso_apartment_fields.yml, conf/cmi/core.entity_form_display.node.apartment.default.yml, conf/cmi/core.entity_view_display.node.apartment.default.yml, conf/cmi/core.entity_view_display.node.apartment.teaser.yml, conf/cmi/field.field.node.apartment.field_haso_fee.yml, conf/cmi/field.storage.node.field_haso_fee.yml, conf/cmi/language/fi/field.field.node.apartment.field_haso_fee.yml, conf/cmi/search_api.index.apartment_listing.yml, conf/cmi/views.view.project_apartments_listing.yml, public/modules/custom/asu_content/asu_content.module, public/modules/custom/asu_content/src/BatchService.php, public/modules/custom/asu_content/src/Commands/AsuContentDrushCommands.php, public/modules/custom/asu_csv_import/config/install/asu_csv_import.haso_apartment_fields.yml, public/modules/custom/asu_rest/src/Plugin/rest/resource/ElasticSearch.php, public/themes/custom/asuntotuotanto/templates/content/node--apartment--full.html.twig, public/themes/custom/asuntotuotanto/templates/views/project/views-view-table--project-apartments-listing.html.twig
Revert back SATT-54 ticket related changes which was revert off before production deployment
=> ASU-54: SATT-54: Revert back changes related this ticket

composer.json, composer.lock, conf/cmi/core.extension.yml, conf/cmi/login_history.settings.yml, conf/cmi/ultimate_cron.job.login_history_cron.yml, conf/cmi/views.view.login_history.yml, public/modules/custom/asu_user/src/AuthService.php
Small change / fix on SAML auth hashPid function and also added login history
=> Login related changes & fixes

composer.json, composer.lock, conf/cmi/core.extension.yml, conf/cmi/login_history.settings.yml, conf/cmi/ultimate_cron.job.login_history_cron.yml, conf/cmi/views.view.login_history.yml, public/modules/custom/asu_application/src/Form/ApplicationForm.php, public/modules/custom/asu_user/src/AuthService.php
Some minor login related changes / fixes to production. These changes are on develop but we cant merge develop to master so these changes are cherry picked
=> Asu x login related to prod

public/modules/custom/asu_api/asu_api.module, public/modules/custom/asu_api/src/Api/BackendApi/Request/GetApartmentRevaluationsRequest.php, public/modules/custom/asu_content/src/BatchService.php, public/modules/custom/asu_content/src/Commands/AsuContentDrushCommands.php
Latest changes & fixes related SATT-54 ticket
Original pr and testing guidance found #561 but is good to use production database and compare data to production
=> ASU-54: Latest calculations and changes

public/modules/custom/asu_content/src/BatchService.php
Upon testing found out that there is a need for new cases.
- Calculation for field_haso_fee was missing if it was the only missing field.
- field_right_of_occupancy_payment was not being emptied after moving the value to field_haso_fee
=> SATT-54 Tweaked the drush script

.github/workflows/artifact.yml, .github/workflows/test.yml, .github/workflows/update-config.yml
Update Github check & tests
https://andersinno.atlassian.net/browse/SATT-69
=> SATT-69: Update github check & tests

.github/workflows/artifact.yml
=> SATT-69: fetch-depth 1

.github/workflows/artifact.yml
Revert actions/checkout@v4 to v3 and actions/upload-artifact@v4 to v3
=> SATT-69: revert v4 to v3

.github/workflows/artifact.yml
Revert PHP version PHP 8.3 to PHP 8.2
=> SATT-69: PHP 8.3 to PHP 8.2

.github/workflows/artifact.yml
=> SATT-69: mysql to mariadb

.github/workflows/artifact.yml
Adding:
continue-on-error: true
=> SATT-69: continue-on-error

.github/workflows/artifact.yml, public/sites/default/settings.php
Change actions to v4 from v3 and php 8.2 to 8.3 and also adding elastic settings
=> SATT-69: Artifact v3 to v4 and elastic settings

.github/workflows/artifact.yml, public/modules/custom/asu_application/asu_application.info.yml, public/modules/custom/asu_application/asu_application.install
Fix artifact related bug fixes and error
=> SATT-69: github artifact bug fix and helfi user roles install fix

conf/cmi/system.site.yml
Change site default language to finnish. Caused /en redirect problems ...
=> SATT-68: Set fi as default lang

.env, compose.yaml, conf/cmi/core.extension.yml, public/sites/default/settings.php
=> SATT-X: Stage file proxy

composer.json, composer.lock
Fix artifact dump actions. 
Unable to install the <em class="placeholder">Automated Logout</em> module since it requires the <em class="placeholder">JavaScript Cookie Library</em> module.
=> SATT-69: Updated autologout module and js-cookie

conf/cmi/core.extension.yml
=> SATT-69: Enable js cookie

public/sites/default/saml.settings.php
=> SATT-82: variable name typo fix

docker/openshift/notify.php
Added missing openshift/notify.php file
=> Added opensift notify

docker/openshift/notify.php, public/sites/default/saml.settings.php
=> Release 12.9. (2)

public/modules/custom/asu_application/src/EventSubscriber/ApplicationSubscriber.php
`"message":"Error: Call to undefined method Drupal\\asu_application\\EventSubscriber\\ApplicationSubscriber::logger() in Drupal\\asu_application\\EventSubscriber\\ApplicationSubscriber->salesSendApplicationToBackend() (line 240 of /app/public/modules/custom/asu_application/src/EventSubscriber/ApplicationSubscriber.php).","context":{"severity_level":3,"exception":{"class":"Error","message":"Call to undefined method Drupal\\asu_application\\EventSubscriber\\ApplicationSubscriber::logger()","code":0,"file":"/app/public/modules/custom/asu_application/src/EventSubscriber/ApplicationSubscriber.php:240"}}`
- make fresh
- rebuild track information and re-index apartment_list search api index
- go haso listing
- if you have As Oy Helsingin Timezone open that project and edit, …
=> Error: Call to undefined method ApplicationSubscriber::logger()

composer.lock, public/sites/default/settings.php
Update metatag robots noindex to index
=> Metatag index udpate

composer.lock, conf/cmi/autologout.settings.yml, conf/cmi/block.block.asu_admin_content.yml, conf/cmi/block.block.asu_admin_primary_local_tasks.yml, conf/cmi/block.block.asu_admin_secondary_local_tasks.yml, conf/cmi/core.entity_form_display.node.landing_page.default.yml, conf/cmi/media.type.remote_video.yml, conf/cmi/ultimate_cron.job.login_history_cron.yml, conf/cmi/views.view.archive.yml, conf/cmi/views.view.block_content.yml, conf/cmi/views.view.content.yml, conf/cmi/views.view.files.yml, conf/cmi/views.view.glossary.yml, conf/cmi/views.view.locked_content.yml, conf/cmi/views.view.login_history.yml, conf/cmi/views.view.media.yml, conf/cmi/views.view.media_library.yml, conf/cmi/views.view.news.yml, conf/cmi/views.view.paragraphs_library.yml, conf/cmi/views.view.paragraphs_selection.yml, conf/cmi/views.view.redirect.yml, conf/cmi/views.view.redirect_404.yml, conf/cmi/views.view.samlauth_map.yml, conf/cmi/views.view.scheduler_scheduled_content.yml, conf/cmi/views.view.taxonomy_term.yml, conf/cmi/views.view.user_admin_people.yml
Drupal core update 10.3.3 to 10.3.5
https://www.drupal.org/project/drupal/releases/10.3.4
https://www.drupal.org/project/drupal/releases/10.3.5
=> SATT-68: Drupal core update 10.3.5

public/modules/custom/asu_application/src/Form/ApplicationForm.php
Added personal id check on application form and minor applicant error message tweak
- you need to have DRUPAL_AUTH_TOKEN and ASU_DJANGO_BACKEND_URL setup to compose.ayml file
- also you need to have dev database
- make fresh or make drush-cr
- do not login as admin
- drush uli --uid=104
- you shoud have 3 draft application on hakemukset listing
- test sent application with wrong personal id
- you should see error messages
- finally sent application with correct personal id value
- also test additional applicant information with wrong and correct information, you can use same personal id for both main and additional applicant
=> SATT-81: Personal id check to application form

public/modules/custom/asu_application/src/Form/SalespersonApplicationForm.php
Fixing code standard fixes which are related #630 
- make fresh
- rebuild track information and re-index search apartment
- logout
- login as salesperson like uid 85
- login as salesperson
- go user listing page
- filter users by last logged in value
- select tero Äyrämö and click Tee hakemus uudelle käyttäjälle
- now you should see timestamps on application list
- if you open docker logs you should see errors and everything else should work as usually
=> SATT-89 Related code standard fixes

conf/cmi/raven.settings.yml
Update Raven configures send more errors to Sentry
=> SATT-106: Update raven send more errors to Sentry

public/modules/custom/asu_api/src/Api/BackendApi/Request/CreateApplicationRequest.php, public/modules/custom/asu_api/src/Api/BackendApi/Request/SalesCreateApplicationRequest.php
Add applicant  data to create application request to remove ssn_suffix field. 
- make fresh
- index search api indexes
- logout
- login as uid 85
- create application to Tero ayramo (there should be 2 draft which can use)
- sent with correct personal id
- check that application is sent without errors
- logout
- login as tero uid 104
- do application or sent draft application (if you dont have drafts or any open project then you need to login as admin and update project to open)
- check that is goes without error
=> SATT-87: Send all main applicant data to API

public/modules/custom/asu_application/src/Form/ApplicationForm.php, public/modules/custom/asu_rest/src/Plugin/rest/resource/Initialize.php
Performance tweaks based information on Sentry performance
- make fresh
- go search api settings and rebuild track information and re-index both indexes
- logout as admin
- go haso and hitas listing pages and check that everything works
- then login as customer suomi fi or uid=104
- go haso and hitas listing pages and check that everything looks fine and your possible applications are showing in haso and hitas listing pages
=> Satt 109 performance tweaks

public/sites/default/settings.php
Raven public_dsn setting to settings.php
=> SATT-106: raven dsn setting to settings.php

public/sites/default/settings.php
=> SATT-106: update sentry settings

public/sites/default/settings.php
Merge dev and testing environment settings.php to one
=> SATT-117: Dev & test settings.php

public/sites/default/settings.php
Clean dublicate settings on settings.php so every azure environment settings are under one condition
=> SATT-117: settings.php azure env settings to one

public/sites/default/settings.php
Updated elastic authentication settings to settings.php
=> SATT-117: Elastic authentication

public/sites/default/settings.php
Clear elasticsearch_connector cluster settings from settings.php
=> SATT-117: Clear cluster settings

public/sites/default/settings.php
Remove all elastic settings from settings.php
=> SATT-117: Remove elastic settings from settings.php

public/sites/default/settings.php
Revert elastic search settings to settings.php
=> SATT-117: Revert elastic search settings to settings.php

conf/cmi/search_api.server.asuntotuotanto.yml
update search api server asuntotuotanto configuration
=> SATT-117: search api asuntotuotanto server conf update

public/sites/default/settings.php
Remove and change elasticsearch_connector settings on settings.php
=> SATT-117: Remove all elastic cluster settings off

public/sites/default/settings.php
Settings.php server variable typo fixes
=> SATT-117: Settings.php variable check Typo fixes

docker/openshift/Dockerfile
Fix php-ini-overrides.ini path
=> SATT-122: fix file path

docker/openshift/php-ini-overrides.ini
=> SATT-122: typo fix 20000 to 2000

ElasticsearchConnectorTest.php, HelfiConnector.php, elasticsearch_connector.connector.helfi_connector.schema.yml
Originally from https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/189
=> Add custom elasticsearch_connector module that allows self-signed certs

ElasticsearchConnectorTest.php, HelfiConnector.php, composer.json, composer.lock, elasticsearch_connector.connector.helfi_connector.schema.yml, public/.gitignore, public/robots.txt, public/sites/default/settings.php, public/themes/custom/asuntotuotanto/templates/content/node--apartment--full.html.twig, public/themes/custom/asuntotuotanto/templates/content/node--project--full.html.twig
Cherry-pick selected features from develop branch into master for prod update
- **Merge pull request #739 from City-of-Helsinki/ASU-1753**
- **Merge pull request #738 from City-of-Helsinki/ASU-1754**
- **Merge pull request #742 from City-of-Helsinki/ASU-1751**
=> prod update 2025-05-26

.gitignore, conf/cmi/core.entity_form_display.node.project.default.yml, conf/cmi/core.entity_view_display.node.project.default.yml, conf/cmi/core.entity_view_display.node.project.teaser.yml, conf/cmi/core.entity_view_display.node.project.teaser_admin.yml, conf/cmi/core.entity_view_display.node.project.teaser_media_bank.yml, conf/cmi/field.field.node.project.field_can_apply_afterwards.yml, conf/cmi/field.storage.node.field_can_apply_afterwards.yml, conf/cmi/search_api.index.apartment.yml, conf/cmi/search_api.index.apartment_listing.yml, public/modules/custom/asu_application/src/Form/ApplicationForm.php, public/modules/custom/asu_content/src/Entity/Project.php, public/modules/custom/asu_content/translations/fi.po, public/modules/custom/asu_rest/src/Plugin/rest/resource/ElasticSearch.php, public/themes/custom/asuntotuotanto/asuntotuotanto.theme, public/themes/custom/asuntotuotanto/templates/content/node--apartment--full.html.twig
- Add field `can_apply_afterwards`
- Add field `project_can_apply_afterwards` to EL index
=> ASU-1712: Allow applying to HASO apartments after application period has ended
